/**
 * Taksonomi kendaraan komersial Indonesia, 61 archetype.
 *
 * Sumbernya adalah riset armada bertanggal 5 Agustus 2026 yang menyandarkan
 * setiap angka pada regulasi Indonesia (PP 55/2012, PP 79/2013, UU 22/2009,
 * Kepmen PUPR 176/KPTS/M/2025, Permenhub 60/2019) dan spesifikasi resmi OEM.
 * Register sumber lengkapnya ada di `src/content/reference/sources.ts`.
 *
 * Satu prinsip mengatur seluruh berkas ini, dan mengabaikannya membuat data ini
 * berbahaya alih-alih berguna: **nama pasar bukan kelas kapasitas.** "CDD",
 * "fuso", "tronton", dan "wingbox" adalah sebutan dagang, bukan kategori
 * hukum. Tidak ada satu pun angka payload universal yang melekat padanya.
 * Kapasitas sesungguhnya sebuah unit hanya bisa dibaca dari STNK/KIR/SRUT-nya,
 * dari JBI/JBKI yang berlaku, dan dari berat kosong setelah karoseri terpasang.
 *
 * Karena itu setiap angka di sini masuk sebagai **rentang perencanaan**, bukan
 * spesifikasi. Rentang menyatakan ketidakpastian yang memang ada; satu angka
 * tunggal akan menyembunyikannya, dan yang menanggung akibatnya adalah sopir di
 * jembatan timbang.
 *
 * DIHASILKAN dari Master_Kendaraan_Komersial_Indonesia_Cost_per_KM_2026.xlsx.
 * Sunting sumber datanya, bukan berkas ini.
 */

export interface Range {
  min: number;
  max: number;
}

export interface VehicleArchetype {
  /** Kunci stabil, sekaligus anchor tautan pada tabel referensi. */
  id: string;
  /**
   * Already English in the source data ("Light Commercial", "Heavy Truck", ...),
   * so it doubles as its own English label. No `mainClassEn` twin exists
   * because there is nothing left to translate.
   */
  mainClass: string;
  /** Deskripsi teknis netral dalam bahasa Indonesia, tidak memakai nama dagang. */
  commercialType: string;
  commercialTypeEn: string;
  /** Sebutan pasar yang dipakai sehari-hari -- ini yang orang ketik di mesin pencari. */
  marketNames: string;
  marketNamesEn: string;
  /** Kategori kendaraan barang menurut PP 55/2012: N1, N2, N3, atau kategori trailer O. */
  legalCategory: string;
  unitForm: string;
  axleConfig: string;
  totalAxles: string;
  overallLengthM?: number;
  /** Golongan penyeberangan -- ditentukan panjang keseluruhan, bukan jumlah gandar. */
  ferryClass: string;
  /** Golongan tol -- ditentukan jenis kendaraan dan jumlah gandar, bukan panjang. */
  tollClass: string;
  body: string;
  /** Dimensi ruang muat khas dalam meter, bila bodinya memang berbentuk ruang. */
  cargo?: { length: number; width: number; height: number };
  /** Rentang volume perencanaan (m3). Kosong untuk bodi yang tidak diukur dengan volume. */
  planningVolume?: Range;
  /** Rentang payload perencanaan (ton). Bukan rating legal. */
  planningPayload: Range;
  /** Rating GVW/GCW pabrikan (ton) sebagaimana ditulis sumber. */
  rating: string;
  roadClass: string;
  scope: string;
  dataStatus: string;
  notes: string;
  notesEn: string;
  sources: string[];
}

export const VEHICLE_ARCHETYPES: VehicleArchetype[] = [
  {
    id: "CV001",
    mainClass: "Light Commercial",
    commercialType: "Pickup bak terbuka kecil",
    commercialTypeEn: "Small open-bed pickup",
    marketNames: "pickup kecil / bak",
    marketNamesEn: "small pickup / bak",
    legalCategory: "N1",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 4.2,
    ferryClass: "IV-B",
    tollClass: "I",
    body: "Bak terbuka",
    cargo: { length: 2.2, width: 1.45, height: 0.35 },
    planningVolume: { min: 1.1, max: 1.3 },
    planningPayload: { min: 0.7, max: 1.0 },
    rating: "≤3.5",
    roadClass: "I sampai III subject MST",
    scope: "Urban/regional",
    dataStatus: "OEM benchmark",
    notes: "Ukuran bak terbuka, bukan volume ruang tertutup yang bisa dipakai.",
    notesEn: "Open-bed dimensions, not an enclosed usable volume.",
    sources: ["https://www.suzuki.co.id/automobile/new-carry-pick-up", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV002",
    mainClass: "Light Commercial",
    commercialType: "Pickup bak lebar 1 ton",
    commercialTypeEn: "1-ton wide-bed pickup",
    marketNames: "pickup 1 ton / wide deck",
    marketNamesEn: "1-ton pickup / wide deck",
    legalCategory: "N1",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 4.2,
    ferryClass: "IV-B",
    tollClass: "I",
    body: "Bak terbuka",
    cargo: { length: 2.5, width: 1.75, height: 0.43 },
    planningVolume: { min: 1.7, max: 1.9 },
    planningPayload: { min: 0.9, max: 1.2 },
    rating: "≤3.5",
    roadClass: "I sampai III subject MST",
    scope: "Urban/regional",
    dataStatus: "OEM benchmark",
    notes: "Kapasitas muat berbeda menurut varian dan bodi yang terpasang.",
    notesEn: "Load capacity varies by variant and fitted body.",
    sources: ["https://www.suzuki.co.id/automobile/new-carry-pick-up", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV003",
    mainClass: "Light Commercial",
    commercialType: "Pickup berat atau sasis kabin",
    commercialTypeEn: "Heavy pickup or cab-chassis",
    marketNames: "pickup 1.2 ton / cab chassis",
    marketNamesEn: "1.2-ton pickup / cab chassis",
    legalCategory: "N1/N2 boundary",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 5.3,
    ferryClass: "V-B",
    tollClass: "I",
    body: "Bak terbuka atau boks",
    cargo: { length: 2.6, width: 1.7, height: 0.45 },
    planningVolume: { min: 1.8, max: 2.2 },
    planningPayload: { min: 1.0, max: 1.5 },
    rating: "3.0 sampai 4.5",
    roadClass: "I sampai III subject MST",
    scope: "Urban/regional",
    dataStatus: "OEM benchmark + planning",
    notes: "Periksa kategori pada STNK dan JBI yang berlaku.",
    notesEn: "Check the category on the STNK and the applicable JBI.",
    sources: ["https://pressroom.toyota.astra.co.id/hilux-rangga-miliki-payload-12-ton", "https://isuzu-astra.com/product/isuzu-traga/"],
  },
  {
    id: "CV004",
    mainClass: "Light Commercial",
    commercialType: "Van boks tertutup kecil",
    commercialTypeEn: "Small enclosed box van",
    marketNames: "blind van kecil",
    marketNamesEn: "small blind van",
    legalCategory: "N1",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 4.5,
    ferryClass: "IV-B",
    tollClass: "I",
    body: "Van tertutup",
    cargo: { length: 2.5, width: 1.5, height: 1.3 },
    planningVolume: { min: 4.0, max: 4.8 },
    planningPayload: { min: 0.8, max: 1.1 },
    rating: "2.4 sampai 2.8",
    roadClass: "I sampai III subject MST",
    scope: "Urban last-mile",
    dataStatus: "OEM benchmark",
    notes: "Volume yang benar-benar terpakai berkurang oleh rumah roda dan sekat.",
    notesEn: "Usable volume is reduced by wheel housings and partitions.",
    sources: ["https://www.dfskmotors.co.id/id/cars/gelora-e", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV005",
    mainClass: "Light Commercial",
    commercialType: "Van boks tertutup besar atau van listrik",
    commercialTypeEn: "Large enclosed box van or electric van",
    marketNames: "blind van besar / EV van",
    marketNamesEn: "large blind van / EV van",
    legalCategory: "N1",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 5.1,
    ferryClass: "V-B",
    tollClass: "I",
    body: "Van tertutup",
    cargo: { length: 2.7, width: 1.7, height: 1.45 },
    planningVolume: { min: 5.5, max: 6.5 },
    planningPayload: { min: 0.9, max: 1.3 },
    rating: "2.7 sampai 3.5",
    roadClass: "I sampai III subject MST",
    scope: "Urban/regional",
    dataStatus: "OEM benchmark",
    notes: "Berat baterai menurunkan kapasitas muat meski ruang kargonya besar.",
    notesEn: "Battery weight reduces payload capacity even though cargo space is large.",
    sources: ["https://wuling.id/id/mitra-ev", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV006",
    mainClass: "Light Commercial",
    commercialType: "Pickup penggerak empat roda",
    commercialTypeEn: "Four-wheel-drive pickup",
    marketNames: "double cabin / single cabin 4x4",
    marketNamesEn: "double cabin / single cabin 4x4",
    legalCategory: "N1/N2",
    unitForm: "Rigid",
    axleConfig: "4x4",
    totalAxles: "2",
    overallLengthM: 5.3,
    ferryClass: "V-B",
    tollClass: "I",
    body: "Bak terbuka atau bodi layanan",
    cargo: { length: 1.5, width: 1.55, height: 0.45 },
    planningVolume: { min: 0.9, max: 1.3 },
    planningPayload: { min: 0.7, max: 1.2 },
    rating: "3.0 sampai 4.5",
    roadClass: "I sampai III subject MST",
    scope: "Mining support/remote",
    dataStatus: "Planning range",
    notes: "Kabin ganda berkapasitas muat lebih kecil daripada kabin tunggal.",
    notesEn: "Double cab has lower payload capacity than single cab.",
    sources: ["https://pressroom.toyota.astra.co.id/hilux-rangga-miliki-payload-12-ton", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV007",
    mainClass: "Light Truck",
    commercialType: "Truk ringan roda empat, bak pendek",
    commercialTypeEn: "Light four-wheel truck, short bed",
    marketNames: "CDE short / engkel",
    marketNamesEn: "CDE short / engkel",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 5.0,
    ferryClass: "IV-B",
    tollClass: "II",
    body: "Boks atau bak datar",
    cargo: { length: 3.0, width: 1.7, height: 1.7 },
    planningVolume: { min: 7.5, max: 9.0 },
    planningPayload: { min: 1.8, max: 2.8 },
    rating: "5.0 sampai 5.5",
    roadClass: "I sampai III subject MST",
    scope: "Urban/regional",
    dataStatus: "OEM + planning body",
    notes: "Kapasitas muat = JBI dikurangi berat kosong setelah karoseri, awak, dan perlengkapan.",
    notesEn: "Payload capacity = JBI minus curb weight after bodywork, crew, and equipment.",
    sources: ["https://isuzu-astra.com/product/isuzu-elf-nlr/", "https://ktbfuso.co.id/product/canter"],
  },
  {
    id: "CV008",
    mainClass: "Light Truck",
    commercialType: "Truk ringan roda empat, bak panjang",
    commercialTypeEn: "Light four-wheel truck, long bed",
    marketNames: "CDE long / engkel long",
    marketNamesEn: "CDE long / engkel long",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 6.0,
    ferryClass: "V-B",
    tollClass: "II",
    body: "Boks atau bak datar",
    cargo: { length: 4.2, width: 1.8, height: 1.9 },
    planningVolume: { min: 12.5, max: 14.5 },
    planningPayload: { min: 1.8, max: 3.0 },
    rating: "5.0 sampai 6.0",
    roadClass: "I sampai II subject dimensions/MST",
    scope: "Urban/regional",
    dataStatus: "OEM + planning body",
    notes: "Untuk barang ringan, bak panjang akan kehabisan ruang lebih dulu daripada berat.",
    notesEn: "For light cargo, the long bed runs out of space before it runs out of weight capacity.",
    sources: ["https://ktbfuso.co.id/product/canter", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV009",
    mainClass: "Light Truck",
    commercialType: "Truk ringan roda enam, bak standar",
    commercialTypeEn: "Light six-wheel truck, standard bed",
    marketNames: "CDD / double engkel",
    marketNamesEn: "CDD / double engkel",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 6.5,
    ferryClass: "V-B",
    tollClass: "II",
    body: "Boks atau bak datar",
    cargo: { length: 4.5, width: 2.0, height: 2.0 },
    planningVolume: { min: 16.0, max: 19.0 },
    planningPayload: { min: 3.5, max: 5.5 },
    rating: "7.5 sampai 8.5",
    roadClass: "I sampai II subject dimensions/MST",
    scope: "Regional distribution",
    dataStatus: "OEM + planning body",
    notes: "Sebutan pasar, bukan kelas menurut peraturan.",
    notesEn: "A market term, not a regulatory class.",
    sources: ["https://ktbfuso.co.id/product/canter", "https://www.udtrucks.com/indonesia/trucks/quester/specs"],
  },
  {
    id: "CV010",
    mainClass: "Light Truck",
    commercialType: "Truk ringan roda enam, bak panjang",
    commercialTypeEn: "Light six-wheel truck, long bed",
    marketNames: "CDD long",
    marketNamesEn: "CDD long",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 7.5,
    ferryClass: "VI-B",
    tollClass: "II",
    body: "Boks atau wingbox",
    cargo: { length: 5.8, width: 2.1, height: 2.1 },
    planningVolume: { min: 23.0, max: 27.0 },
    planningPayload: { min: 3.0, max: 5.0 },
    rating: "8.0 sampai 8.5",
    roadClass: "I sampai II; verify OAL",
    scope: "Regional distribution",
    dataStatus: "OEM + planning body",
    notes: "Lazim untuk muatan bervolume besar, tetapi JBI tetap yang menentukan.",
    notesEn: "Common for high-volume cargo, but JBI still governs the limit.",
    sources: ["https://ktbfuso.co.id/product/canter", "https://www.udtrucks.com/indonesia/trucks/quester/specs"],
  },
  {
    id: "CV011",
    mainClass: "Light Truck",
    commercialType: "Truk ringan penggerak empat roda",
    commercialTypeEn: "Light four-wheel-drive truck",
    marketNames: "light truck 4WD",
    marketNamesEn: "light truck 4WD",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x4",
    totalAxles: "2",
    overallLengthM: 6.0,
    ferryClass: "V-B",
    tollClass: "II",
    body: "Bak datar, jungkit, atau layanan",
    cargo: { length: 3.8, width: 2.0, height: 1.0 },
    planningVolume: { min: 7.0, max: 9.0 },
    planningPayload: { min: 2.5, max: 4.5 },
    rating: "7.5 sampai 9.0",
    roadClass: "I sampai II subject MST",
    scope: "Remote/construction",
    dataStatus: "Planning range",
    notes: "Kemampuan medan berat tidak menaikkan batas muat legal di jalan umum.",
    notesEn: "Off-road capability does not raise the legal load limit on public roads.",
    sources: ["https://ktbfuso.co.id/product/canter", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV012",
    mainClass: "Light Truck",
    commercialType: "Truk jungkit ringan",
    commercialTypeEn: "Light tipper truck",
    marketNames: "dump engkel / dump CDD",
    marketNamesEn: "dump engkel / dump CDD",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 6.2,
    ferryClass: "V-B",
    tollClass: "II",
    body: "Bak jungkit",
    cargo: { length: 3.6, width: 2.0, height: 0.8 },
    planningVolume: { min: 5.0, max: 6.5 },
    planningPayload: { min: 3.0, max: 5.5 },
    rating: "7.5 sampai 8.5",
    roadClass: "I sampai II subject MST",
    scope: "Construction/quarry",
    dataStatus: "Planning range",
    notes: "Kerapatan material yang menentukan berat muat. Kubikasi bak bukan kapasitas berat.",
    notesEn: "Material density determines load weight. Bed cubic capacity is not weight capacity.",
    sources: ["https://ktbfuso.co.id/product/canter", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV013",
    mainClass: "Light Truck",
    commercialType: "Truk berpendingin ringan",
    commercialTypeEn: "Light refrigerated truck",
    marketNames: "reefer CDE/CDD",
    marketNamesEn: "reefer CDE/CDD",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 6.5,
    ferryClass: "V-B",
    tollClass: "II",
    body: "Boks berpendingin berinsulasi",
    cargo: { length: 4.2, width: 1.85, height: 1.85 },
    planningVolume: { min: 12.0, max: 15.0 },
    planningPayload: { min: 2.0, max: 4.0 },
    rating: "7.5 sampai 8.5",
    roadClass: "I sampai II subject MST",
    scope: "Cold chain",
    dataStatus: "Planning range",
    notes: "Insulasi dan unit pendingin mengurangi volume dalam sekaligus kapasitas muat.",
    notesEn: "Insulation and the refrigeration unit reduce both internal volume and payload capacity.",
    sources: ["https://ktbfuso.co.id/product/canter", "https://www.cma-cgm.com/assets/public/documents/Container%20Technical%20Brochures.pdf"],
  },
  {
    id: "CV014",
    mainClass: "Light Truck",
    commercialType: "Truk tangki ringan",
    commercialTypeEn: "Light tanker truck",
    marketNames: "tangki engkel/CDD",
    marketNamesEn: "tanker engkel/CDD",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 6.5,
    ferryClass: "V-B",
    tollClass: "II",
    body: "Tangki cairan",
    planningVolume: { min: 4.0, max: 8.0 },
    planningPayload: { min: 3.0, max: 5.5 },
    rating: "7.5 sampai 8.5",
    roadClass: "I sampai II; dangerous-goods rules as relevant",
    scope: "Fuel/water/food liquid",
    dataStatus: "Planning range",
    notes: "Pakai satuan liter. Kompartemen, kerapatan cairan, dan efek goyangan ikut menentukan.",
    notesEn: "Use liter units. Compartmentation, liquid density, and surge effects also matter.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019"],
  },
  {
    id: "CV015",
    mainClass: "Light Truck",
    commercialType: "Truk pengangkut bak lepas ringan",
    commercialTypeEn: "Light detachable-container (roll-off) truck",
    marketNames: "armroll kecil",
    marketNamesEn: "small armroll",
    legalCategory: "N2",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 6.5,
    ferryClass: "V-B",
    tollClass: "II",
    body: "Bak kontainer lepas",
    cargo: { length: 3.0, width: 1.8, height: 1.2 },
    planningVolume: { min: 5.0, max: 8.0 },
    planningPayload: { min: 2.5, max: 4.5 },
    rating: "7.5 sampai 8.5",
    roadClass: "I sampai II subject MST",
    scope: "Waste/industrial",
    dataStatus: "Planning range",
    notes: "Kapasitas muat sudah termasuk berat kosong kontainernya.",
    notesEn: "Payload capacity already includes the container's own tare weight.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV016",
    mainClass: "Medium Truck",
    commercialType: "Truk medium bergandar dua, bodi boks",
    commercialTypeEn: "Two-axle medium truck, box body",
    marketNames: "fuso engkel / medium box",
    marketNamesEn: "fuso engkel / medium box",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 8.0,
    ferryClass: "VI-B",
    tollClass: "II",
    body: "Boks",
    cargo: { length: 6.0, width: 2.3, height: 2.3 },
    planningVolume: { min: 30.0, max: 34.0 },
    planningPayload: { min: 6.0, max: 10.0 },
    rating: "10 sampai 16",
    roadClass: "I sampai II; class III dimension often exceeded",
    scope: "Regional/intercity",
    dataStatus: "OEM + planning body",
    notes: "Kapasitas muat sangat berbeda menurut sasis dan bodinya.",
    notesEn: "Payload capacity varies significantly by chassis and body.",
    sources: ["https://isuzu-astra.com/product/isuzu-giga/", "https://ktbfuso.co.id/product/fighter-x"],
  },
  {
    id: "CV017",
    mainClass: "Medium Truck",
    commercialType: "Truk medium bergandar dua, bodi wingbox",
    commercialTypeEn: "Two-axle medium truck, wingbox body",
    marketNames: "wingbox 4x2",
    marketNamesEn: "wingbox 4x2",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 9.5,
    ferryClass: "VI-B",
    tollClass: "II",
    body: "Wingbox atau sisi tirai",
    cargo: { length: 7.5, width: 2.35, height: 2.4 },
    planningVolume: { min: 40.0, max: 45.0 },
    planningPayload: { min: 5.5, max: 9.0 },
    rating: "14 sampai 16",
    roadClass: "I sampai II",
    scope: "Intercity distribution",
    dataStatus: "Planning range",
    notes: "Mekanisme buka samping dan struktur atap mengurangi volume efektifnya.",
    notesEn: "The side-opening mechanism and roof structure reduce effective volume.",
    sources: ["https://ktbfuso.co.id/product/fighter-x", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV018",
    mainClass: "Medium Truck",
    commercialType: "Truk medium bergandar dua, bak datar",
    commercialTypeEn: "Two-axle medium truck, flatbed",
    marketNames: "flatbed fuso",
    marketNamesEn: "flatbed fuso",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 9.0,
    ferryClass: "VI-B",
    tollClass: "II",
    body: "Bak datar dengan tiang",
    planningPayload: { min: 7.0, max: 11.0 },
    rating: "14 sampai 16",
    roadClass: "I sampai II",
    scope: "Machinery/steel/general cargo",
    dataStatus: "Planning range",
    notes: "Tidak berbentuk ruang tertutup. Pakai loading meter, luas tapak, dan batas pengikatan muatan.",
    notesEn: "Not an enclosed space. Use loading meters, footprint area, and load-securing limits.",
    sources: ["https://ktbfuso.co.id/product/fighter-x", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV019",
    mainClass: "Medium Truck",
    commercialType: "Truk medium bergandar dua, bak jungkit",
    commercialTypeEn: "Two-axle medium truck, tipper",
    marketNames: "dump fuso",
    marketNamesEn: "dump fuso",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 8.0,
    ferryClass: "VI-B",
    tollClass: "II",
    body: "Bak jungkit",
    cargo: { length: 5.0, width: 2.3, height: 1.2 },
    planningVolume: { min: 12.0, max: 15.0 },
    planningPayload: { min: 7.0, max: 11.0 },
    rating: "14 sampai 16",
    roadClass: "I sampai II subject MST",
    scope: "Construction/quarry",
    dataStatus: "Planning range",
    notes: "Kapasitas muat dibatasi kerapatan material dan sebaran beban sumbu.",
    notesEn: "Payload capacity is limited by material density and axle-load distribution.",
    sources: ["https://ktbfuso.co.id/product/fighter-x", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV020",
    mainClass: "Medium Truck",
    commercialType: "Truk medium bergandar dua, tangki",
    commercialTypeEn: "Two-axle medium truck, tanker",
    marketNames: "tangki 4x2",
    marketNamesEn: "tanker 4x2",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 9.0,
    ferryClass: "VI-B",
    tollClass: "II",
    body: "Tangki cairan",
    planningVolume: { min: 8.0, max: 14.0 },
    planningPayload: { min: 7.0, max: 11.0 },
    rating: "14 sampai 16",
    roadClass: "I sampai II; dangerous-goods rules as relevant",
    scope: "Liquid bulk",
    dataStatus: "Planning range",
    notes: "Volume tangki dinyatakan dalam m³ atau liter. Kerapatan cairan yang menentukan tonasenya.",
    notesEn: "Tank volume is stated in m³ or liters. Liquid density determines the tonnage.",
    sources: ["https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV021",
    mainClass: "Medium Truck",
    commercialType: "Truk molen bergandar dua",
    commercialTypeEn: "Two-axle concrete mixer truck",
    marketNames: "mixer 4x2",
    marketNamesEn: "mixer 4x2",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 8.5,
    ferryClass: "VI-B",
    tollClass: "II",
    body: "Drum molen",
    planningVolume: { min: 4.0, max: 6.0 },
    planningPayload: { min: 7.0, max: 10.0 },
    rating: "14 sampai 18",
    roadClass: "I sampai II subject MST",
    scope: "Ready-mix",
    dataStatus: "Planning range",
    notes: "Volume nominal drum berbeda dari kapasitas adukan sesungguhnya.",
    notesEn: "Nominal drum volume differs from actual mixed-load capacity.",
    sources: ["https://www.hino.co.id/", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV022",
    mainClass: "Medium/Heavy Truck",
    commercialType: "Truk bergandar tiga, bodi boks panjang",
    commercialTypeEn: "Three-axle truck, long box body",
    marketNames: "tronton 6x2 box",
    marketNamesEn: "tronton 6x2 box",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "6x2",
    totalAxles: "3",
    overallLengthM: 11.5,
    ferryClass: "VII",
    tollClass: "III",
    body: "Boks atau wingbox",
    cargo: { length: 8.5, width: 2.4, height: 2.5 },
    planningVolume: { min: 48.0, max: 55.0 },
    planningPayload: { min: 10.0, max: 16.0 },
    rating: "22 sampai 26",
    roadClass: "I only typically; OAL >9m",
    scope: "Intercity high-volume",
    dataStatus: "OEM + planning body",
    notes: "Konfigurasi sumbu angkat atau sumbu bantu berbeda-beda antar unit.",
    notesEn: "Lift-axle or auxiliary-axle configuration varies by unit.",
    sources: ["https://www.udtrucks.com/indonesia/trucks/quester/specs", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV023",
    mainClass: "Medium/Heavy Truck",
    commercialType: "Truk bergandar tiga pengangkut mobil",
    commercialTypeEn: "Three-axle car-carrier truck",
    marketNames: "car carrier tronton",
    marketNamesEn: "car carrier tronton",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "6x2",
    totalAxles: "3",
    overallLengthM: 12.0,
    ferryClass: "VII",
    tollClass: "III",
    body: "Pengangkut bertingkat",
    planningPayload: { min: 8.0, max: 14.0 },
    rating: "22 sampai 26",
    roadClass: "I only typically",
    scope: "Automotive logistics",
    dataStatus: "Planning range",
    notes: "Kapasitas dinyatakan dalam jumlah unit kendaraan dan geometri deknya, bukan meter kubik.",
    notesEn: "Capacity is stated in number of vehicle units and deck geometry, not cubic meters.",
    sources: ["https://www.hino.co.id/", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV024",
    mainClass: "Heavy Truck",
    commercialType: "Truk bergandar tiga penggerak ganda, bak jungkit",
    commercialTypeEn: "Three-axle dual-drive truck, tipper",
    marketNames: "tronton dump 6x4",
    marketNamesEn: "tronton dump 6x4",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "6x4",
    totalAxles: "3",
    overallLengthM: 9.0,
    ferryClass: "VI-B",
    tollClass: "III",
    body: "Bak jungkit berat",
    cargo: { length: 5.5, width: 2.35, height: 1.5 },
    planningVolume: { min: 16.0, max: 22.0 },
    planningPayload: { min: 14.0, max: 20.0 },
    rating: "24 sampai 26",
    roadClass: "I sampai II subject MST/route",
    scope: "Construction/mining support",
    dataStatus: "OEM + planning body",
    notes: "Kapasitas di lokasi kerja bisa melebihi batas jalan umum. Jangan mencampur keduanya.",
    notesEn: "On-site capacity can exceed the public-road limit. Do not conflate the two.",
    sources: ["https://ktbfuso.co.id/product/fighter-x", "https://www.udtrucks.com/indonesia/trucks/quester/specs"],
  },
  {
    id: "CV025",
    mainClass: "Heavy Truck",
    commercialType: "Truk molen bergandar tiga",
    commercialTypeEn: "Three-axle concrete mixer truck",
    marketNames: "mixer tronton",
    marketNamesEn: "mixer tronton",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "6x4",
    totalAxles: "3",
    overallLengthM: 9.5,
    ferryClass: "VI-B",
    tollClass: "III",
    body: "Drum molen",
    planningVolume: { min: 6.0, max: 10.0 },
    planningPayload: { min: 12.0, max: 18.0 },
    rating: "24 sampai 30",
    roadClass: "I sampai II subject MST/route",
    scope: "Ready-mix",
    dataStatus: "Planning range",
    notes: "Kapasitas muat di jalan bisa berbeda dari spesifikasi di lokasi kerja.",
    notesEn: "On-road payload capacity can differ from the on-site specification.",
    sources: ["https://www.hino.co.id/", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV026",
    mainClass: "Heavy Truck",
    commercialType: "Truk bergandar tiga pengangkut kayu gelondongan",
    commercialTypeEn: "Three-axle log truck",
    marketNames: "logging truck / truck kayu",
    marketNamesEn: "logging truck / truck kayu",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "6x4",
    totalAxles: "3",
    overallLengthM: 11.5,
    ferryClass: "VII",
    tollClass: "III",
    body: "Penopang dan tiang pengikat",
    planningPayload: { min: 12.0, max: 18.0 },
    rating: "24 sampai 30",
    roadClass: "I; special cargo controls may apply",
    scope: "Forestry/long cargo",
    dataStatus: "Planning range",
    notes: "Julur muatan dan cara pengikatannya harus diperiksa.",
    notesEn: "Load overhang and securing method must be checked.",
    sources: ["https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV027",
    mainClass: "Heavy Truck",
    commercialType: "Truk bergandar empat, sasis panjang",
    commercialTypeEn: "Four-axle truck, long chassis",
    marketNames: "trintin 8x2 / 4 axle long",
    marketNamesEn: "trintin 8x2 / 4 axle long",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "8x2",
    totalAxles: "4",
    overallLengthM: 11.95,
    ferryClass: "VII",
    tollClass: "IV",
    body: "Boks, bak datar, atau pengangkut mobil",
    cargo: { length: 9.0, width: 2.4, height: 2.5 },
    planningVolume: { min: 52.0, max: 60.0 },
    planningPayload: { min: 16.0, max: 24.0 },
    rating: "30 sampai 32",
    roadClass: "I only typically",
    scope: "High-volume/heavy intercity",
    dataStatus: "OEM benchmark + planning",
    notes: "Contoh dari pabrikan: konfigurasi 8x2 dengan berat kotor 32 ton.",
    notesEn: "OEM example: 8x2 configuration with 32-ton gross weight.",
    sources: ["https://www.hino.co.id/", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV028",
    mainClass: "Heavy Truck",
    commercialType: "Truk bergandar empat, bak jungkit berat",
    commercialTypeEn: "Four-axle truck, heavy-duty tipper",
    marketNames: "dump 8x4 / mining road truck",
    marketNamesEn: "dump 8x4 / mining road truck",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "8x4",
    totalAxles: "4",
    overallLengthM: 10.5,
    ferryClass: "VII",
    tollClass: "IV",
    body: "Bak jungkit berat",
    cargo: { length: 6.5, width: 2.45, height: 1.7 },
    planningVolume: { min: 22.0, max: 30.0 },
    planningPayload: { min: 20.0, max: 32.0 },
    rating: "32 sampai 41",
    roadClass: "I/special route; road JBI governs",
    scope: "Mining/construction",
    dataStatus: "OEM benchmark + planning",
    notes: "Berat kotor menurut pabrikan tidak dengan sendirinya sama dengan JBI yang diizinkan di jalan.",
    notesEn: "OEM-rated gross weight does not automatically equal the JBI permitted on public roads.",
    sources: ["https://www.udtrucks.com/indonesia/trucks/quester/specs", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV029",
    mainClass: "Heavy Truck",
    commercialType: "Truk bergandar empat, molen atau pompa beton",
    commercialTypeEn: "Four-axle truck, concrete mixer or concrete pump",
    marketNames: "mixer/pompa beton 8x4",
    marketNamesEn: "mixer/concrete pump 8x4",
    legalCategory: "N3",
    unitForm: "Rigid",
    axleConfig: "8x4",
    totalAxles: "4",
    overallLengthM: 12.0,
    ferryClass: "VII",
    tollClass: "IV",
    body: "Struktur molen atau pompa beton",
    planningVolume: { min: 8.0, max: 12.0 },
    planningPayload: { min: 18.0, max: 28.0 },
    rating: "32 sampai 41",
    roadClass: "I/special route",
    scope: "Construction",
    dataStatus: "Planning range",
    notes: "Pakai berat peralatan dan beban sumbu yang sesungguhnya.",
    notesEn: "Use actual equipment weight and axle loads.",
    sources: ["https://www.hino.co.id/", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV030",
    mainClass: "Heavy/Special Truck",
    commercialType: "Truk bergandar lima, sasis khusus",
    commercialTypeEn: "Five-axle truck, special chassis",
    marketNames: "5-axle rigid special",
    marketNamesEn: "5-axle rigid special",
    legalCategory: "N3 special",
    unitForm: "Rigid",
    axleConfig: "10x4/10x6",
    totalAxles: "5",
    overallLengthM: 12.0,
    ferryClass: "VII",
    tollClass: "V",
    body: "Crane, pompa, atau alat berat",
    planningPayload: { min: 20.0, max: 40.0 },
    rating: "40 sampai 60",
    roadClass: "Special route/permit dependent",
    scope: "Heavy construction",
    dataStatus: "Planning range",
    notes: "Sangat bergantung pada rute dan izin. Dimensi pastinya berbeda-beda.",
    notesEn: "Highly dependent on route and permit. Exact dimensions vary by unit.",
    sources: ["https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV031",
    mainClass: "Tractor-Semitrailer",
    commercialType: "Tractor head bergandar dua dengan trailer dua gandar",
    commercialTypeEn: "Two-axle tractor head with a two-axle semi-trailer",
    marketNames: "trailer 4 gandar total",
    marketNamesEn: "4-axle-total trailer",
    legalCategory: "N3 + O4",
    unitForm: "Combination",
    axleConfig: "4x2 + 2 axle",
    totalAxles: "4",
    overallLengthM: 15.5,
    ferryClass: "VIII",
    tollClass: "IV",
    body: "Trailer serbaguna",
    cargo: { length: 12.0, width: 2.45, height: 2.6 },
    planningVolume: { min: 70.0, max: 80.0 },
    planningPayload: { min: 18.0, max: 26.0 },
    rating: "GCW 30 sampai 38",
    roadClass: "I; combination <=18m unless special",
    scope: "Long-haul",
    dataStatus: "Planning range",
    notes: "Jumlah gandar untuk golongan tol dihitung dari tractor head dan trailernya sekaligus.",
    notesEn: "The toll axle count is taken from the tractor head and trailer combined.",
    sources: ["https://www.udtrucks.com/indonesia/trucks/quester/specs", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV032",
    mainClass: "Tractor-Semitrailer",
    commercialType: "Tractor head bergandar dua dengan trailer tiga gandar",
    commercialTypeEn: "Two-axle tractor head with a three-axle semi-trailer",
    marketNames: "trailer 5 gandar total",
    marketNamesEn: "5-axle-total trailer",
    legalCategory: "N3 + O4",
    unitForm: "Combination",
    axleConfig: "4x2 + 3 axle",
    totalAxles: "5",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Trailer serbaguna",
    cargo: { length: 12.0, width: 2.45, height: 2.6 },
    planningVolume: { min: 70.0, max: 90.0 },
    planningPayload: { min: 20.0, max: 30.0 },
    rating: "GCW 36 sampai 45",
    roadClass: "I; combination <=18m unless special",
    scope: "Long-haul/container",
    dataStatus: "Planning range",
    notes: "Umumnya golongan tol V karena bergandar lima.",
    notesEn: "Typically toll class V, since the combination runs five axles.",
    sources: ["https://www.udtrucks.com/indonesia/trucks/quester/specs", "https://jdih.pu.go.id/internal/assets/assets/produk/KepmenPUPR/2025/02/2025kmpu176.pdf"],
  },
  {
    id: "CV033",
    mainClass: "Tractor-Semitrailer",
    commercialType: "Tractor head bergandar tiga dengan trailer tiga gandar",
    commercialTypeEn: "Three-axle tractor head with a three-axle semi-trailer",
    marketNames: "trailer 6 gandar / tag axle",
    marketNamesEn: "6-axle trailer / tag axle",
    legalCategory: "N3 + O4",
    unitForm: "Combination",
    axleConfig: "6x2 + 3 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Trailer serbaguna",
    cargo: { length: 12.0, width: 2.45, height: 2.6 },
    planningVolume: { min: 70.0, max: 90.0 },
    planningPayload: { min: 22.0, max: 32.0 },
    rating: "GCW 40 sampai 50",
    roadClass: "I; route/JBI dependent",
    scope: "Long-haul",
    dataStatus: "Planning range",
    notes: "Sumbu tambahan memperbaiki sebaran beban, bukan menaikkan batas muat legal secara otomatis.",
    notesEn: "The extra axle improves load distribution; it does not automatically raise the legal load limit.",
    sources: ["https://www.udtrucks.com/indonesia/trucks/quester/specs", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV034",
    mainClass: "Tractor-Semitrailer",
    commercialType: "Tractor head penggerak ganda dengan trailer tiga gandar",
    commercialTypeEn: "Dual-drive-axle tractor head with a three-axle semi-trailer",
    marketNames: "prime mover 6x4 + trailer",
    marketNamesEn: "6x4 prime mover + trailer",
    legalCategory: "N3 + O4",
    unitForm: "Combination",
    axleConfig: "6x4 + 3 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Trailer serbaguna",
    cargo: { length: 12.0, width: 2.45, height: 2.6 },
    planningVolume: { min: 70.0, max: 90.0 },
    planningPayload: { min: 22.0, max: 36.0 },
    rating: "GCW 45 sampai 60",
    roadClass: "I; route/JBI dependent",
    scope: "Heavy long-haul",
    dataStatus: "OEM + planning",
    notes: "Pakai GCW, JBI atau JBKI, dan beban sumbu, bukan tenaga mesin saja.",
    notesEn: "Size it on GCW, JBI or JBKI, and axle load -- not on engine power alone.",
    sources: ["https://ktbfuso.co.id/product/fighter-x", "https://www.udtrucks.com/indonesia/trucks/quester/specs"],
  },
  {
    id: "CV035",
    mainClass: "Container Chassis",
    commercialType: "Trailer rangka kontainer 20 kaki",
    commercialTypeEn: "20-foot container chassis trailer",
    marketNames: "trailer container 20 feet",
    marketNamesEn: "20-foot container trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "2 sampai 3 axle",
    totalAxles: "5",
    overallLengthM: 12.0,
    ferryClass: "VII",
    tollClass: "V",
    body: "Sasis kunci putar kontainer 20 kaki",
    cargo: { length: 5.896, width: 2.35, height: 2.393 },
    planningVolume: { min: 33.0, max: 33.0 },
    planningPayload: { min: 18.0, max: 28.2 },
    rating: "Container gross up to 30.48",
    roadClass: "I; route/JBI dependent",
    scope: "Container drayage",
    dataStatus: "Container official spec",
    notes: "Payload kontainer adalah batas peralatan. JBI jalan di Indonesia bisa lebih rendah.",
    notesEn: "Container payload is the equipment limit. Indonesia's on-road JBI can be lower.",
    sources: ["https://www.maersk.com/~/media_sc9/maersk/local-information/files/africa/south-africa/important-information/container-type-and-sizes/dry-equipment-specifications-updated.pdf", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV036",
    mainClass: "Container Chassis",
    commercialType: "Trailer rangka kontainer 40 atau 45 kaki",
    commercialTypeEn: "40- or 45-foot container chassis trailer",
    marketNames: "trailer container 40/45 feet",
    marketNamesEn: "40/45-foot container trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "3 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Sasis kunci putar kontainer 40 atau 45 kaki",
    cargo: { length: 12.032, width: 2.35, height: 2.697 },
    planningVolume: { min: 67.0, max: 85.0 },
    planningPayload: { min: 18.0, max: 29.0 },
    rating: "Container gross 30.48 sampai 32.5",
    roadClass: "I; route/JBI dependent",
    scope: "Container drayage",
    dataStatus: "Container official spec",
    notes: "Kubikasi 40 HC sekitar 76 m³ dan 45 HC sekitar 85 m³, tetapi batas jalan tetap yang menentukan.",
    notesEn: "40 HC cubic capacity runs around 76 m³ and 45 HC around 85 m³, but the road limit still governs.",
    sources: ["https://www.maersk.com/~/media_sc9/maersk/local-information/files/africa/south-africa/important-information/container-type-and-sizes/dry-equipment-specifications-updated.pdf", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV037",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer bak datar",
    commercialTypeEn: "Flatbed trailer",
    marketNames: "flatbed trailer / loss bak",
    marketNamesEn: "flatbed trailer / open deck",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "2 sampai 3 axle",
    totalAxles: "5",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Dek datar",
    planningPayload: { min: 20.0, max: 35.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I; special if oversize cargo",
    scope: "Steel/machinery/project",
    dataStatus: "Planning range",
    notes: "Pakai loading meter, luas tapak, beban titik, dan kapasitas pengikatan.",
    notesEn: "Size it on loading meters, footprint area, point loads, and tie-down capacity.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019"],
  },
  {
    id: "CV038",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer bodi boks tertutup",
    commercialTypeEn: "Enclosed box-body trailer",
    marketNames: "box trailer",
    marketNamesEn: "box trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "2 sampai 3 axle",
    totalAxles: "5",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Boks tertutup",
    cargo: { length: 12.0, width: 2.45, height: 2.6 },
    planningVolume: { min: 75.0, max: 90.0 },
    planningPayload: { min: 18.0, max: 28.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I",
    scope: "General cargo",
    dataStatus: "Planning range",
    notes: "Dimensi dalam sesungguhnya bergantung pada bangunan bodinya.",
    notesEn: "Actual internal dimensions depend on how the body is built.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://www.maersk.com/~/media_sc9/maersk/local-information/files/africa/south-africa/important-information/container-type-and-sizes/dry-equipment-specifications-updated.pdf"],
  },
  {
    id: "CV039",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer bersisi tirai atau wingbox",
    commercialTypeEn: "Curtain-side or wingbox trailer",
    marketNames: "wingbox trailer / curtain side",
    marketNamesEn: "wingbox trailer / curtain side",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "3 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Sisi tirai atau wingbox",
    cargo: { length: 12.0, width: 2.45, height: 2.6 },
    planningVolume: { min: 75.0, max: 90.0 },
    planningPayload: { min: 18.0, max: 28.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I",
    scope: "FMCG/industrial",
    dataStatus: "Planning range",
    notes: "Perangkat buka samping mengurangi ruang muat yang bisa dipakai.",
    notesEn: "The side-opening mechanism reduces usable load space.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV040",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer berpendingin",
    commercialTypeEn: "Refrigerated trailer",
    marketNames: "reefer trailer",
    marketNamesEn: "reefer trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "3 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Ruang berpendingin berinsulasi",
    cargo: { length: 12.0, width: 2.4, height: 2.45 },
    planningVolume: { min: 65.0, max: 82.0 },
    planningPayload: { min: 16.0, max: 26.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I",
    scope: "Cold chain",
    dataStatus: "Planning + container reference",
    notes: "Unit pendingin, insulasi, dan tangki bahan bakar mengurangi kapasitas muat sekaligus kubikasi.",
    notesEn: "The refrigeration unit, insulation, and fuel tank cut into both payload and cubic capacity.",
    sources: ["https://www.cma-cgm.com/assets/public/documents/Container%20Technical%20Brochures.pdf", "https://www.maersk.com/support/faqs/cargo-weight-limit"],
  },
  {
    id: "CV041",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer tangki cairan",
    commercialTypeEn: "Liquid tanker trailer",
    marketNames: "tangki trailer",
    marketNamesEn: "tanker trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "2 sampai 4 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Tangki berkompartemen",
    planningVolume: { min: 20.0, max: 40.0 },
    planningPayload: { min: 18.0, max: 32.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I; dangerous-goods controls as relevant",
    scope: "Fuel/chemical/food liquid",
    dataStatus: "Planning range",
    notes: "Kapasitas dinyatakan dalam liter atau m³. Kerapatan cairan dan batas kompartemen yang menentukan tonasenya.",
    notesEn: "Capacity is stated in liters or m³. Liquid density and compartment limits determine the tonnage.",
    sources: ["https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV042",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer silo untuk muatan curah kering",
    commercialTypeEn: "Silo trailer for dry bulk cargo",
    marketNames: "bulk powder / cement tanker",
    marketNamesEn: "bulk powder / cement tanker",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "3 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Silo bertekanan",
    planningVolume: { min: 30.0, max: 60.0 },
    planningPayload: { min: 18.0, max: 30.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I",
    scope: "Cement/flour/powder",
    dataStatus: "Planning range",
    notes: "Kerapatan material curah dan berat perlengkapan pneumatik ikut menentukan.",
    notesEn: "Bulk material density and the weight of the pneumatic equipment both factor in.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV043",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer jungkit belakang",
    commercialTypeEn: "Rear-tipping dump trailer",
    marketNames: "dump trailer belakang",
    marketNamesEn: "rear dump trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "3 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Jungkit belakang",
    cargo: { length: 9.0, width: 2.45, height: 1.8 },
    planningVolume: { min: 25.0, max: 45.0 },
    planningPayload: { min: 20.0, max: 35.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I; site/route limits",
    scope: "Bulk/mining/construction",
    dataStatus: "Planning range",
    notes: "Titik berat tinggi saat menumpah, sehingga pengendalian di lokasi sangat menentukan.",
    notesEn: "The center of gravity rises sharply while tipping, so on-site control is critical.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV044",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer jungkit samping",
    commercialTypeEn: "Side-tipping dump trailer",
    marketNames: "side tipper trailer",
    marketNamesEn: "side tipper trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "3 axle",
    totalAxles: "6",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Jungkit samping",
    cargo: { length: 9.0, width: 2.45, height: 1.5 },
    planningVolume: { min: 22.0, max: 38.0 },
    planningPayload: { min: 20.0, max: 34.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I; site/route limits",
    scope: "Bulk/mining",
    dataStatus: "Planning range",
    notes: "Ruang bebas samping dan kestabilan tanah menjadi kendala operasionalnya.",
    notesEn: "Side clearance and ground stability are the operating constraints.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV045",
    mainClass: "Special Trailer",
    commercialType: "Trailer dek rendah leher tetap",
    commercialTypeEn: "Fixed-neck low-deck trailer",
    marketNames: "lowbed / lowboy",
    marketNamesEn: "lowbed / lowboy",
    legalCategory: "O4 special",
    unitForm: "Semi-trailer",
    axleConfig: "2 sampai 4 axle",
    totalAxles: "6",
    overallLengthM: 16.0,
    ferryClass: "VIII",
    tollClass: "V",
    body: "Dek rendah",
    planningPayload: { min: 20.0, max: 50.0 },
    rating: "JBKI/route dependent",
    roadClass: "Special cargo permit if dimensions/weight exceed standard",
    scope: "Heavy equipment",
    dataStatus: "Planning range",
    notes: "Dek rendah menolong untuk muatan tinggi, tetapi lebar dan panjangnya bisa masuk kategori muatan berdimensi khusus.",
    notesEn: "The low deck helps with tall cargo, but width and length can still put it in the oversize-cargo category.",
    sources: ["https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019", "https://www.faymonville.com/products/"],
  },
  {
    id: "CV046",
    mainClass: "Special Trailer",
    commercialType: "Trailer dek rendah leher lepas",
    commercialTypeEn: "Detachable-neck low-deck trailer",
    marketNames: "lowbed DGN / RGN",
    marketNamesEn: "lowbed DGN / RGN",
    legalCategory: "O4 special",
    unitForm: "Semi-trailer",
    axleConfig: "3 sampai 6 axle",
    totalAxles: "8",
    overallLengthM: 18.0,
    ferryClass: "IX",
    tollClass: "V",
    body: "Dek rendah yang dapat dilepas",
    planningPayload: { min: 30.0, max: 80.0 },
    rating: "JBKI/route dependent",
    roadClass: "Special route/permit",
    scope: "Heavy equipment",
    dataStatus: "Planning range",
    notes: "Pemuatan dari depan menurunkan sudut ramp, tetapi rangkaiannya bisa melebihi 18 meter.",
    notesEn: "Front loading lowers the ramp angle, but the combination can run past 18 meters.",
    sources: ["https://www.faymonville.com/products/", "https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019"],
  },
  {
    id: "CV047",
    mainClass: "Special Trailer",
    commercialType: "Trailer dek datar atau rendah yang bisa dipanjangkan",
    commercialTypeEn: "Extendable flat- or low-deck trailer",
    marketNames: "extendable trailer",
    marketNamesEn: "extendable trailer",
    legalCategory: "O4 special",
    unitForm: "Semi-trailer",
    axleConfig: "3 sampai 10 axle",
    totalAxles: "8",
    overallLengthM: 25.0,
    ferryClass: "IX",
    tollClass: "V",
    body: "Dek teleskopik",
    planningPayload: { min: 30.0, max: 100.0 },
    rating: "Route-dependent",
    roadClass: "Special route/permit",
    scope: "Long cargo/wind blade",
    dataStatus: "Manufacturer benchmark + planning",
    notes: "Panjang saat dipanjangkan harus dinilai dalam konfigurasi operasional sesungguhnya.",
    notesEn: "Extended length must be assessed in the actual operating configuration.",
    sources: ["https://www.faymonville.com/products/", "https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019"],
  },
  {
    id: "CV048",
    mainClass: "Special Trailer",
    commercialType: "Trailer batang panjang dengan dolly dapat dikemudikan",
    commercialTypeEn: "Pole trailer with a steerable dolly",
    marketNames: "pole trailer / dolly",
    marketNamesEn: "pole trailer / dolly",
    legalCategory: "O4 special",
    unitForm: "Combination",
    axleConfig: "multi-axle",
    totalAxles: "6",
    overallLengthM: 25.0,
    ferryClass: "IX",
    tollClass: "V",
    body: "Penopang terpisah dengan dolly",
    planningPayload: { min: 20.0, max: 80.0 },
    rating: "Route-dependent",
    roadClass: "Special route/permit",
    scope: "Long beams/pipes/transformer",
    dataStatus: "Planning range",
    notes: "Panjang keseluruhan dan geometri kemudi belakang yang paling menentukan.",
    notesEn: "Overall length and the rear-steering geometry are the deciding factors.",
    sources: ["https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV049",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer pengangkut mobil",
    commercialTypeEn: "Car-carrier trailer",
    marketNames: "car carrier trailer",
    marketNamesEn: "car carrier trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "2 sampai 3 axle",
    totalAxles: "5",
    overallLengthM: 18.0,
    ferryClass: "IX",
    tollClass: "V",
    body: "Pengangkut bertingkat",
    planningPayload: { min: 15.0, max: 25.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I or special if >18 m",
    scope: "Automotive logistics",
    dataStatus: "Planning range",
    notes: "Kapasitas dihitung dalam jumlah kendaraan. Tinggi totalnya kerap mendekati batas maksimum.",
    notesEn: "Capacity is counted in vehicle units. Overall height often runs close to the maximum limit.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV050",
    mainClass: "Semi-trailer Body",
    commercialType: "Trailer pengangkut ternak",
    commercialTypeEn: "Livestock trailer",
    marketNames: "trailer ternak",
    marketNamesEn: "livestock trailer",
    legalCategory: "O4",
    unitForm: "Semi-trailer",
    axleConfig: "2 sampai 3 axle",
    totalAxles: "5",
    overallLengthM: 16.5,
    ferryClass: "IX",
    tollClass: "V",
    body: "Bertingkat berventilasi",
    cargo: { length: 12.0, width: 2.45, height: 2.6 },
    planningVolume: { min: 70.0, max: 90.0 },
    planningPayload: { min: 15.0, max: 25.0 },
    rating: "GCW/JBKI dependent",
    roadClass: "I; animal-welfare controls",
    scope: "Livestock",
    dataStatus: "Planning range",
    notes: "Sebaran beban hidup dan ventilasinya berbeda dari kargo umum.",
    notesEn: "Live-load distribution and ventilation needs differ from general cargo.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV051",
    mainClass: "Specialized Rigid",
    commercialType: "Truk dengan crane terpasang",
    commercialTypeEn: "Truck with a mounted crane",
    marketNames: "crane truck / truck crane",
    marketNamesEn: "crane truck / truck-mounted crane",
    legalCategory: "N2/N3",
    unitForm: "Rigid",
    axleConfig: "4x2 sampai 10x4",
    totalAxles: "4",
    overallLengthM: 12.0,
    ferryClass: "VII",
    tollClass: "IV",
    body: "Crane dengan dek datar",
    planningPayload: { min: 3.0, max: 25.0 },
    rating: "8 sampai 60",
    roadClass: "Standard or special by actual dimensions/axles",
    scope: "Construction/project",
    dataStatus: "Planning range",
    notes: "Kapasitas angkat crane bukan kapasitas muat di jalan.",
    notesEn: "Crane lifting capacity is not the same as road payload capacity.",
    sources: ["https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV052",
    mainClass: "Specialized Rigid",
    commercialType: "Truk derek dan penyelamatan kendaraan",
    commercialTypeEn: "Vehicle towing and recovery truck",
    marketNames: "towing / car carrier recovery",
    marketNamesEn: "towing / recovery vehicle carrier",
    legalCategory: "N2/N3",
    unitForm: "Rigid",
    axleConfig: "4x2 sampai 6x4",
    totalAxles: "3",
    overallLengthM: 10.0,
    ferryClass: "VI-B",
    tollClass: "III",
    body: "Pengangkat bawah atau baki miring",
    planningPayload: { min: 3.0, max: 18.0 },
    rating: "8 sampai 30",
    roadClass: "I sampai II or I by axles/length",
    scope: "Vehicle recovery",
    dataStatus: "Planning range",
    notes: "Berat gabungan dengan kendaraan yang diderek harus tetap di dalam batas rating.",
    notesEn: "Combined weight with the towed vehicle must stay within the rating.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV053",
    mainClass: "Specialized Rigid",
    commercialType: "Truk pemadat sampah",
    commercialTypeEn: "Garbage compactor truck",
    marketNames: "garbage compactor",
    marketNamesEn: "garbage compactor",
    legalCategory: "N2/N3",
    unitForm: "Rigid",
    axleConfig: "4x2 sampai 6x4",
    totalAxles: "3",
    overallLengthM: 10.0,
    ferryClass: "VI-B",
    tollClass: "III",
    body: "Bak pemadat",
    planningVolume: { min: 6.0, max: 25.0 },
    planningPayload: { min: 3.0, max: 12.0 },
    rating: "8 sampai 26",
    roadClass: "I sampai II subject MST",
    scope: "Municipal waste",
    dataStatus: "Planning range",
    notes: "Volume bak nominal berbeda dari berat sampah setelah dipadatkan.",
    notesEn: "Nominal body volume differs from the weight of the waste after compaction.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV054",
    mainClass: "Specialized Rigid",
    commercialType: "Truk penyedot limbah cair",
    commercialTypeEn: "Liquid-waste vacuum truck",
    marketNames: "vacuum truck / sedot limbah",
    marketNamesEn: "vacuum truck / septic tanker",
    legalCategory: "N2/N3",
    unitForm: "Rigid",
    axleConfig: "4x2 sampai 6x4",
    totalAxles: "3",
    overallLengthM: 10.0,
    ferryClass: "VI-B",
    tollClass: "III",
    body: "Tangki vakum",
    planningVolume: { min: 4.0, max: 20.0 },
    planningPayload: { min: 3.0, max: 15.0 },
    rating: "8 sampai 26",
    roadClass: "I sampai II; hazardous-waste rules as relevant",
    scope: "Waste/industrial",
    dataStatus: "Planning range",
    notes: "Kerapatan cairan atau lumpur dan sertifikasi tangki ikut menentukan.",
    notesEn: "Liquid or sludge density and the tank's certification both factor in.",
    sources: ["https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV055",
    mainClass: "Specialized Rigid",
    commercialType: "Truk bengkel keliling atau kendaraan layanan",
    commercialTypeEn: "Mobile workshop or service truck",
    marketNames: "service truck / workshop mobile",
    marketNamesEn: "service truck / mobile workshop",
    legalCategory: "N2/N3",
    unitForm: "Rigid",
    axleConfig: "4x2 sampai 6x4",
    totalAxles: "3",
    overallLengthM: 10.0,
    ferryClass: "VI-B",
    tollClass: "III",
    body: "Bodi layanan atau genset",
    cargo: { length: 6.0, width: 2.4, height: 2.4 },
    planningVolume: { min: 20.0, max: 45.0 },
    planningPayload: { min: 2.0, max: 12.0 },
    rating: "8 sampai 26",
    roadClass: "I sampai II",
    scope: "Mining/field service",
    dataStatus: "Planning range",
    notes: "Kapasitas muat sudah termasuk perkakas, genset, tangki, dan suku cadang.",
    notesEn: "Payload capacity already includes tools, genset, tanks, and spare parts.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
  {
    id: "CV056",
    mainClass: "Heavy Haul",
    commercialType: "Tractor head pemberat dengan trailer modular",
    commercialTypeEn: "Ballasted tractor head with a modular trailer",
    marketNames: "prime mover heavy haul + modular",
    marketNamesEn: "heavy-haul prime mover + modular trailer",
    legalCategory: "N3 + O4 special",
    unitForm: "Combination",
    axleConfig: "6x4/8x4 + multi-axle",
    totalAxles: "10",
    overallLengthM: 30.0,
    ferryClass: "IX",
    tollClass: "V",
    body: "Rangkaian angkutan berat",
    planningPayload: { min: 80.0, max: 500.0 },
    rating: "Project-specific",
    roadClass: "Route survey + special permit/escort",
    scope: "Transformer/reactor/project cargo",
    dataStatus: "Manufacturer benchmark",
    notes: "Bukan kelas kendaraan jalan biasa. Perlu kajian teknik proyek.",
    notesEn: "Not a standard road-vehicle class. Requires project engineering study.",
    sources: ["https://www.faymonville.com/products/", "https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019"],
  },
  {
    id: "CV057",
    mainClass: "Heavy Haul",
    commercialType: "Trailer platform modular hidrolik",
    commercialTypeEn: "Hydraulic modular platform trailer",
    marketNames: "hydraulic modular trailer",
    marketNamesEn: "hydraulic modular trailer",
    legalCategory: "O4 special",
    unitForm: "Modular trailer",
    axleConfig: "multi-axle lines",
    totalAxles: "12",
    overallLengthM: 30.0,
    ferryClass: "IX",
    tollClass: "V",
    body: "Platform modular hidrolik",
    planningPayload: { min: 100.0, max: 1000.0 },
    rating: "Project-specific",
    roadClass: "Route/site engineered movement",
    scope: "Ultra-heavy cargo",
    dataStatus: "Manufacturer benchmark",
    notes: "Kapasitas bergantung pada jumlah baris sumbu, konfigurasi, dan daya dukung tanah.",
    notesEn: "Capacity depends on the number of axle lines, configuration, and ground bearing capacity.",
    sources: ["https://www.faymonville.com/products/", "https://peraturan.bpk.go.id/Details/139673/permenhub-no-60-tahun-2019"],
  },
  {
    id: "CV058",
    mainClass: "Heavy Haul",
    commercialType: "Platform modular bergerak sendiri",
    commercialTypeEn: "Self-propelled modular platform",
    marketNames: "self-propelled modular transporter",
    marketNamesEn: "self-propelled modular transporter (SPMT)",
    legalCategory: "Special/site equipment",
    unitForm: "Self-propelled",
    axleConfig: "multi-axle lines",
    totalAxles: "24",
    overallLengthM: 30.0,
    ferryClass: "IX",
    tollClass: "V",
    body: "Platform modular bergerak sendiri",
    planningPayload: { min: 100.0, max: 1020.0 },
    rating: "Project-specific",
    roadClass: "Primarily port/site; public-road movement needs authority approval",
    scope: "Ultra-heavy/shipyard/plant",
    dataStatus: "Manufacturer benchmark",
    notes: "Contoh dari pabrikan: 24 baris sumbu dengan kapasitas teknis 1.020 ton.",
    notesEn: "Manufacturer example: 24 axle lines with a technical capacity of 1,020 tonnes.",
    sources: ["https://www.cometto.com/news/news/24-axle-lines-spmt-with-technical-payload-of-1020-tonnes", "https://www.cometto.com/products/self-propelled-vehicles/eco1000"],
  },
  {
    id: "CV059",
    mainClass: "Off-Highway",
    commercialType: "Truk jungkit tambang rigid",
    commercialTypeEn: "Rigid mining dump truck",
    marketNames: "off-highway rigid dump",
    marketNamesEn: "off-highway rigid dump truck",
    legalCategory: "Site equipment",
    unitForm: "Rigid",
    axleConfig: "4x2",
    totalAxles: "2",
    overallLengthM: 10.0,
    ferryClass: "N/A / site",
    tollClass: "N/A / site",
    body: "Bak jungkit tambang",
    planningVolume: { min: 35.0, max: 250.0 },
    planningPayload: { min: 30.0, max: 360.0 },
    rating: "Site rating",
    roadClass: "Not standard public-road operation",
    scope: "Mining/quarry",
    dataStatus: "Planning taxonomy",
    notes: "Tidak dihitung memakai model biaya jalan, tol, maupun penyeberangan biasa.",
    notesEn: "Not costed using standard road, toll, or ferry cost models.",
    sources: ["https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV060",
    mainClass: "Off-Highway",
    commercialType: "Truk jungkit artikulasi",
    commercialTypeEn: "Articulated dump truck",
    marketNames: "ADT / articulated hauler",
    marketNamesEn: "ADT / articulated hauler",
    legalCategory: "Site equipment",
    unitForm: "Articulated",
    axleConfig: "6x6",
    totalAxles: "3",
    overallLengthM: 11.0,
    ferryClass: "N/A / site",
    tollClass: "N/A / site",
    body: "Bak jungkit artikulasi",
    planningVolume: { min: 15.0, max: 35.0 },
    planningPayload: { min: 20.0, max: 60.0 },
    rating: "Site rating",
    roadClass: "Not standard public-road operation",
    scope: "Mining/earthmoving",
    dataStatus: "Planning taxonomy",
    notes: "Pakai model biaya per siklus di lokasi kerja, bukan model biaya per kilometer jalan.",
    notesEn: "Use a per-cycle site cost model, not a per-kilometer road cost model.",
    sources: ["https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf", "https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf"],
  },
  {
    id: "CV061",
    mainClass: "Special Combination",
    commercialType: "Rangkaian dua trailer",
    commercialTypeEn: "Two-trailer combination",
    marketNames: "B-double / double trailer",
    marketNamesEn: "B-double / double trailer",
    legalCategory: "Special/site",
    unitForm: "Combination",
    axleConfig: "multi-unit",
    totalAxles: "8",
    overallLengthM: 25.0,
    ferryClass: "N/A / site",
    tollClass: "N/A / site",
    body: "Dua trailer dengan dolly",
    planningVolume: { min: 100.0, max: 180.0 },
    planningPayload: { min: 30.0, max: 60.0 },
    rating: "Project/site-specific",
    roadClass: "Not standard general-road combination; authority/site approval",
    scope: "Industrial/site",
    dataStatus: "Planning taxonomy",
    notes: "Bukan konfigurasi yang berlaku umum di jalan Indonesia; perlu izin dan kajian tersendiri.",
    notesEn: "Not a combination generally permitted on Indonesian public roads; requires separate permits and study.",
    sources: ["https://peraturan.bpk.go.id/Download/35169/PP%20Nomor%2055%20Tahun%202012.pdf", "https://peraturan.bpk.go.id/Download/27961/UU%20Nomor%2022%20Tahun%202009.pdf"],
  },
]

const byId = new Map(VEHICLE_ARCHETYPES.map((v) => [v.id, v]));

export function getArchetype(id: string): VehicleArchetype | undefined {
  return byId.get(id);
}

/** Urutan tampil kelas utama, dari armada teringan ke yang paling berat. */
export const VEHICLE_CLASS_ORDER: string[] = [
  "Light Commercial",
  "Light Truck",
  "Medium Truck",
  "Medium/Heavy Truck",
  "Heavy Truck",
  "Heavy/Special Truck",
  "Specialized Rigid",
  "Tractor-Semitrailer",
  "Container Chassis",
  "Semi-trailer Body",
  "Special Trailer",
  "Special Combination",
  "Heavy Haul",
  "Off-Highway",
];

/**
 * Nama kelompok dalam bahasa yang dipakai orang, untuk ditampilkan.
 *
 * Kunci dataset tetap memakai istilah sumber agar bisa ditelusuri balik ke
 * risetnya, tetapi tidak ada satu pun dari istilah itu yang layak muncul di
 * halaman publik. Pengunjung mencari "truk besar", bukan "Heavy/Special Truck",
 * dan halaman yang berbicara dengan kosakata internalnya sendiri terbaca
 * seperti dokumen yang bocor, bukan seperti alat bantu.
 */
export const VEHICLE_CLASS_LABELS: Record<string, string> = {
  "Light Commercial": "Kendaraan niaga ringan",
  "Light Truck": "Truk ringan",
  "Medium Truck": "Truk medium",
  "Medium/Heavy Truck": "Truk medium besar",
  "Heavy Truck": "Truk besar",
  "Heavy/Special Truck": "Truk besar khusus",
  "Specialized Rigid": "Truk dengan peralatan khusus",
  "Tractor-Semitrailer": "Tractor head dan trailer",
  "Container Chassis": "Chassis kontainer",
  "Semi-trailer Body": "Bodi trailer",
  "Special Trailer": "Trailer khusus",
  "Special Combination": "Rangkaian khusus",
  "Heavy Haul": "Angkutan alat berat",
  "Off-Highway": "Kendaraan non-jalan raya",
};

export function classLabel(mainClass: string): string {
  return VEHICLE_CLASS_LABELS[mainClass] || mainClass;
}

export function archetypesByClass(mainClass: string): VehicleArchetype[] {
  return VEHICLE_ARCHETYPES.filter((v) => v.mainClass === mainClass);
}

/** Volume ruang muat dari dimensi, bukan dari rentang perencanaan. */
export function cargoVolume(vehicle: VehicleArchetype): number | undefined {
  if (!vehicle.cargo) return undefined;
  return vehicle.cargo.length * vehicle.cargo.width * vehicle.cargo.height;
}

/**
 * Archetype yang layak jadi pilihan pada kalkulator muatan.
 *
 * Bodi tanpa ruang tertutup -- flatbed, tanker, lowbed, SPMT -- sengaja
 * disaring keluar. Kalkulator yang menawarkan "berapa kardus muat di tangki"
 * bukan sekadar tidak berguna; ia mengajarkan satuan kapasitas yang keliru
 * untuk bodi tersebut. Body_Types pada sumber data menyebutnya eksplisit:
 * tidak setiap kendaraan pantas dinyatakan dalam meter kubik.
 */
const NOT_CARTON_LOADABLE = new Set([
  // Container chassis: what gets loaded is the container, and the container
  // page already answers that question with the right internal dimensions.
  "CV035",
  "CV036",
  // Livestock: measured in head per deck area, never in cartons.
  "CV050",
]);

export function loadableArchetypes(): VehicleArchetype[] {
  return VEHICLE_ARCHETYPES.filter(
    (v) => v.cargo !== undefined && v.planningVolume !== undefined && !NOT_CARTON_LOADABLE.has(v.id),
  );
}

/**
 * Menjaga agar setiap kelas pada VEHICLE_CLASS_ORDER benar-benar ada, dan
 * sebaliknya. Kelas yang salah eja hanya akan menghilang dari halaman
 * referensi tanpa error -- persis jenis cacat yang tidak terlihat saat dibaca.
 */
function assertClassOrderIntegrity(): void {
  const present = new Set(VEHICLE_ARCHETYPES.map((v) => v.mainClass));
  const ordered = new Set(VEHICLE_CLASS_ORDER);

  for (const cls of present) {
    if (!ordered.has(cls)) throw new Error(`Vehicle class "${cls}" is missing from VEHICLE_CLASS_ORDER`);
  }
  for (const cls of ordered) {
    if (!present.has(cls)) throw new Error(`VEHICLE_CLASS_ORDER lists an unused class: "${cls}"`);
  }

  const seen = new Set<string>();
  for (const vehicle of VEHICLE_ARCHETYPES) {
    if (seen.has(vehicle.id)) throw new Error(`Duplicate vehicle archetype id: ${vehicle.id}`);
    seen.add(vehicle.id);

    // `xxxEn` being *present* is already enforced by the type; an empty
    // string still satisfies that type and would render as a blank card in
    // English mode, silently, for whoever happens to have the toggle on.
    if (!vehicle.commercialTypeEn.trim()) throw new Error(`${vehicle.id}: commercialTypeEn is empty`);
    if (!vehicle.marketNamesEn.trim()) throw new Error(`${vehicle.id}: marketNamesEn is empty`);
    if (!vehicle.notesEn.trim()) throw new Error(`${vehicle.id}: notesEn is empty`);
  }
}

assertClassOrderIntegrity();
