/**
 * Transactional email HTML templates and their label helpers.
 *
 * Kept separate from src/lib/storage.ts so they can be rendered on the server
 * (app/api/inquiry) without pulling in the browser Supabase client, which
 * throws at module load when the NEXT_PUBLIC_* env vars are absent. The type
 * imports below are erased at compile time, so there is no runtime dependency
 * back on storage.ts.
 */

import type { Inquiry, Questionnaire, Meeting, EmailLog } from "./storage";
import { getAppBaseUrl } from "./appUrl";
import { companyAddressLine } from "./companyInfo";

// Helper to generate beautifully styled HTML emails
export function generateHtmlEmailTemplate(type: EmailLog['type'], data: {
  inquiry: Inquiry;
  questionnaire?: Questionnaire;
  meeting?: Meeting;
}): string {
  const { inquiry, questionnaire, meeting } = data;
  const isEn = inquiry.lang === 'en';
  const baseUrl = getAppBaseUrl();
  const brandTeal = "#0097b2";
  const brandOrange = "#ff5e14";
  const bgSlate = "#f8fafc";

  const headerHtml = `
    <div style="background-color: ${brandTeal}; padding: 24px; text-align: center; border-top-left-radius: 12px; border-top-right-radius: 12px;">
      <h1 style="color: #ffffff; margin: 0; font-family: 'Space Grotesk', 'Helvetica Neue', Arial, sans-serif; font-size: 24px; font-weight: 800; letter-spacing: -0.02em;">
        Cargo<span style="color: #ffffff;">Grid</span> <span style="font-size: 11px; font-weight: 400; letter-spacing: 0.15em; background: rgba(255,255,255,0.2); padding: 3px 8px; border-radius: 4px; vertical-align: middle; margin-left: 8px;">OPERATING SYSTEM</span>
      </h1>
    </div>
  `;

  const footerHtml = isEn ? `
    <div style="background-color: #0f172a; padding: 24px; text-align: center; border-bottom-left-radius: 12px; border-bottom-right-radius: 12px; font-family: 'Inter', Arial, sans-serif; color: #94a3b8; font-size: 11px; line-height: 1.6;">
      <p style="margin: 0 0 8px 0; font-weight: bold; color: #ffffff;">CargoGrid Logistics Enterprise Suite</p>
      <p style="margin: 0 0 12px 0;">${companyAddressLine.en}</p>
      <p style="margin: 0; border-top: 1px solid #334155; padding-top: 12px;">
        This email was automatically generated by the CargoGrid OS system. Please do not reply directly to this address.
      </p>
    </div>
  ` : `
    <div style="background-color: #0f172a; padding: 24px; text-align: center; border-bottom-left-radius: 12px; border-bottom-right-radius: 12px; font-family: 'Inter', Arial, sans-serif; color: #94a3b8; font-size: 11px; line-height: 1.6;">
      <p style="margin: 0 0 8px 0; font-weight: bold; color: #ffffff;">CargoGrid Logistics Enterprise Suite</p>
      <p style="margin: 0 0 12px 0;">${companyAddressLine.id}</p>
      <p style="margin: 0; border-top: 1px solid #334155; padding-top: 12px;">
        Email ini dikirimkan secara otomatis oleh sistem CargoGrid OS. Mohon tidak membalas langsung ke alamat ini.
      </p>
    </div>
  `;

  const containerStyle = `
    background-color: ${bgSlate};
    padding: 24px;
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    color: #334155;
    line-height: 1.6;
    font-size: 14px;
    max-width: 600px;
    margin: 0 auto;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.05);
  `;

  switch (type) {
    case 'customer_welcome':
      return isEn ? `
        <div style="${containerStyle}">
          ${headerHtml}
          <div style="background-color: #ffffff; padding: 32px 24px; font-family: sans-serif;">
            <p style="font-size: 16px; font-weight: bold; margin-top: 0; color: #0f172a;">Dear ${inquiry.name},</p>
            <p style="color: #475569; margin-bottom: 24px;">
              Thank you for registering your company for the <strong>Logistics System Audit & 30-Day Working Pilot</strong> program with CargoGrid OS. Your registration has been successfully received.
            </p>

            <div style="background-color: #f1f5f9; border-left: 4px solid ${brandTeal}; padding: 16px; margin-bottom: 24px; border-radius: 4px;">
              <h3 style="margin: 0 0 8px 0; font-size: 12px; text-transform: uppercase; tracking-wider; color: #475569;">Initial Data Summary</h3>
              <table style="width: 100%; font-size: 13px; border-collapse: collapse;">
                <tr><td style="padding: 4px 0; color: #64748b; width: 40%;">Company:</td><td style="padding: 4px 0; font-weight: bold; color: #1e293b;">${inquiry.company}</td></tr>
                <tr><td style="padding: 4px 0; color: #64748b;">Monthly Volume:</td><td style="padding: 4px 0; font-weight: bold; color: #1e293b;">${inquiry.shipmentVolume} shipments / month</td></tr>
                <tr><td style="padding: 4px 0; color: #64748b;">Primary Challenge:</td><td style="padding: 4px 0; font-weight: bold; color: #ef4444;">${getPainLabel(inquiry.biggestPain, 'en')}</td></tr>
              </table>
            </div>

            <p style="color: #475569; margin-bottom: 24px;">
              To assist the CargoGrid Logistics Consulting team in analyzing your operational profile in depth prior to our qualification meeting, <strong>please take 5 minutes to complete the detailed requirements questionnaire</strong> via the button below:
            </p>

            <div style="text-align: center; margin: 32px 0;">
              <a href="${baseUrl}/#questionnaire?id=${inquiry.id}" style="background-color: ${brandOrange}; color: #ffffff; padding: 14px 28px; font-weight: bold; text-decoration: none; border-radius: 9999px; font-size: 14px; display: inline-block; box-shadow: 0 4px 6px rgba(255, 94, 20, 0.25);">
                Complete Detailed Questionnaire &rarr;
              </a>
            </div>

            <p style="font-size: 12px; color: #94a3b8; text-align: center; margin-bottom: 0;">
              The form can be saved as a <strong>Draft</strong> so you can resume editing at any time.
            </p>
          </div>
          ${footerHtml}
        </div>
      ` : `
        <div style="${containerStyle}">
          ${headerHtml}
          <div style="background-color: #ffffff; padding: 32px 24px; font-family: sans-serif;">
            <p style="font-size: 16px; font-weight: bold; margin-top: 0; color: #0f172a;">Halo Bapak/Ibu ${inquiry.name},</p>
            <p style="color: #475569; margin-bottom: 24px;">
              Terima kasih telah mengajukan registrasi untuk program <strong>Audit Sistem Logistik & Pilot Kerja 30 Hari</strong> bersama CargoGrid OS. Registrasi Anda telah kami terima dengan sukses.
            </p>

            <div style="background-color: #f1f5f9; border-left: 4px solid ${brandTeal}; padding: 16px; margin-bottom: 24px; border-radius: 4px;">
              <h3 style="margin: 0 0 8px 0; font-size: 12px; text-transform: uppercase; tracking-wider; color: #475569;">Ringkasan Data Awal</h3>
              <table style="width: 100%; font-size: 13px; border-collapse: collapse;">
                <tr><td style="padding: 4px 0; color: #64748b; width: 40%;">Perusahaan:</td><td style="padding: 4px 0; font-weight: bold; color: #1e293b;">${inquiry.company}</td></tr>
                <tr><td style="padding: 4px 0; color: #64748b;">Volume:</td><td style="padding: 4px 0; font-weight: bold; color: #1e293b;">${inquiry.shipmentVolume} shipment / bulan</td></tr>
                <tr><td style="padding: 4px 0; color: #64748b;">Kendala Utama:</td><td style="padding: 4px 0; font-weight: bold; color: #ef4444;">${getPainLabel(inquiry.biggestPain, 'id')}</td></tr>
              </table>
            </div>

            <p style="color: #475569; margin-bottom: 24px;">
              Untuk membantu tim Konsultan Logistik CargoGrid menganalisis profil operasional secara mendalam sebelum meeting konfirmasi, <strong>mohon luangkan waktu 5 menit untuk mengisi Formulir Kuesioner & Kebutuhan Detil</strong> melalui link tombol di bawah ini:
            </p>

            <div style="text-align: center; margin: 32px 0;">
              <a href="${baseUrl}/#questionnaire?id=${inquiry.id}" style="background-color: ${brandOrange}; color: #ffffff; padding: 14px 28px; font-weight: bold; text-decoration: none; border-radius: 9999px; font-size: 14px; display: inline-block; box-shadow: 0 4px 6px rgba(255, 94, 20, 0.25);">
                Lengkapi Kuesioner Kebutuhan Detail &rarr;
              </a>
            </div>

            <p style="font-size: 12px; color: #94a3b8; text-align: center; margin-bottom: 0;">
              Formulir dapat disimpan sebagai <strong>Draft</strong> untuk dilanjutkan pengisiannya secara bertahap kapan saja.
            </p>
          </div>
          ${footerHtml}
        </div>
      `;

    case 'admin_alert_new':
      return `
        <div style="${containerStyle}">
          <div style="background-color: #ef4444; padding: 24px; text-align: center; border-top-left-radius: 12px; border-top-right-radius: 12px;">
            <h1 style="color: #ffffff; margin: 0; font-family: sans-serif; font-size: 20px; font-weight: bold;">
              🚨 ${isEn ? "NEW SYSTEM INQUIRY RECEIVED" : "INQUIRY BARU MASUK"}
            </h1>
          </div>
          <div style="background-color: #ffffff; padding: 32px 24px; font-family: sans-serif;">
            <p style="font-size: 15px; margin-top: 0; color: #0f172a;">Yth. Supreme Admin CargoGrid,</p>
            <p style="color: #475569;">
              ${isEn ? "A new logistics prospect has registered initial system audit details via the Landing Page (English):" : "Sebuah prospek sistem logistik baru saja mendaftarkan data awal audit melalui Landing Page:"}
            </p>

            <table style="width: 100%; font-size: 13px; border-collapse: collapse; margin: 20px 0; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
              <tr style="background-color: #f8fafc;"><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #64748b; font-weight: bold;">${isEn ? "Contact Name" : "Nama Kontak"}</td><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #1e293b;">${inquiry.name} (${inquiry.role})</td></tr>
              <tr><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #64748b; font-weight: bold;">${isEn ? "Company" : "Perusahaan"}</td><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #1e293b;">${inquiry.company}</td></tr>
              <tr style="background-color: #f8fafc;"><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #64748b; font-weight: bold;">${isEn ? "WA / Email Info" : "Kontak WA / Email"}</td><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-family: monospace; font-weight: bold; color: #1e293b;">${inquiry.phone} / ${inquiry.email}</td></tr>
              <tr><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #64748b; font-weight: bold;">${isEn ? "Logistics Sector" : "Sektor Logistik"}</td><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #1e293b;">${getSektorLabel(inquiry.companyType, isEn ? 'en' : 'id')}</td></tr>
              <tr style="background-color: #f8fafc;"><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; color: #64748b; font-weight: bold;">${isEn ? "Shipment Volume" : "Volume Pengiriman"}</td><td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #1e293b;">${inquiry.shipmentVolume} shipments / month</td></tr>
              <tr><td style="padding: 10px; color: #64748b; font-weight: bold;">${isEn ? "Core Pain Point" : "Penyebab Masalah"}</td><td style="padding: 10px; font-weight: bold; color: #ef4444;">${getPainLabel(inquiry.biggestPain, isEn ? 'en' : 'id')}</td></tr>
            </table>

            <p style="color: #475569; margin-bottom: 24px;">
              ${isEn ? "The system has sent an English detailed questionnaire email to the customer. Track their progress from the dashboard." : "Sistem telah mengirimkan email kuesioner detail ke customer secara otomatis. Pantau aktivitas prospek melalui panel kontrol admin."}
            </p>

            <div style="text-align: center; margin-top: 24px;">
              <a href="${baseUrl}/#admin" style="background-color: #0f172a; color: #ffffff; padding: 12px 24px; font-weight: bold; text-decoration: none; border-radius: 8px; font-size: 13px; display: inline-block;">
                ${isEn ? "Open Admin Dashboard &rarr;" : "Buka Admin Dashboard &rarr;"}
              </a>
            </div>
          </div>
          ${footerHtml}
        </div>
      `;

    case 'admin_alert_complete':
      return `
        <div style="${containerStyle}">
          <div style="background-color: #10b981; padding: 24px; text-align: center; border-top-left-radius: 12px; border-top-right-radius: 12px;">
            <h1 style="color: #ffffff; margin: 0; font-family: sans-serif; font-size: 20px; font-weight: bold;">
              ✅ ${isEn ? "DETAILED QUESTIONNAIRE COMPLETED" : "KUESIONER KEBUTUHAN SELESAI"}
            </h1>
          </div>
          <div style="background-color: #ffffff; padding: 32px 24px; font-family: sans-serif;">
            <p style="font-size: 15px; margin-top: 0; color: #0f172a;">Yth. Supreme Admin CargoGrid,</p>
            <p style="color: #475569;">
              ${isEn ? `Great news! <strong>${inquiry.company}</strong> has completed all steps of the detailed requirements questionnaire.` : `Kabar baik! Perusahaan <strong>${inquiry.company}</strong> telah melengkapi seluruh tahapan kuesioner kebutuhan secara detail.`}
            </p>

            <div style="background-color: #ecfdf5; border-left: 4px solid #10b981; padding: 16px; margin: 20px 0; border-radius: 4px;">
              <h4 style="margin: 0 0 8px 0; color: #065f46; font-size: 13px;">${isEn ? "Requirements Highlights" : "Sorotan Kebutuhan Prospek"}</h4>
              <p style="font-size: 12px; margin: 0 0 8px 0; color: #047857;">
                <strong>${isEn ? "Desired Modules:" : "Modul CargoGrid Diminati:"}</strong> ${(questionnaire?.desiredModules || []).map(m => getModuleLabel(m, isEn ? 'en' : 'id')).join(', ')}
              </p>
              <p style="font-size: 12px; margin: 0 0 8px 0; color: #047857;">
                <strong>ERP System:</strong> ${questionnaire?.erpSystem || 'None'}
              </p>
              <p style="font-size: 12px; margin: 0; color: #047857;">
                <strong>${isEn ? "Preferred Slots:" : "Preferensi Pertemuan:"}</strong> ${(questionnaire?.preferredSlots || []).join(' OR ')}
              </p>
            </div>

            <p style="color: #475569; margin-bottom: 24px;">
              ${isEn ? "Please review their operational draft answers, select one of the preferred slots, attach the meeting URL, and send the official invite." : "Harap segera setujui salah satu jadwal meeting preferensi customer di atas, lampirkan URL link meeting online, dan kirim undangan meeting resmi."}
            </p>

            <div style="text-align: center;">
              <a href="${baseUrl}/#admin" style="background-color: #10b981; color: #ffffff; padding: 12px 24px; font-weight: bold; text-decoration: none; border-radius: 8px; font-size: 13px; display: inline-block;">
                ${isEn ? "Schedule Consultation Now &rarr;" : "Jadwalkan Pertemuan Sekarang &rarr;"}
              </a>
            </div>
          </div>
          ${footerHtml}
        </div>
      `;

    case 'customer_meeting':
      return isEn ? `
        <div style="${containerStyle}">
          ${headerHtml}
          <div style="background-color: #ffffff; padding: 32px 24px; font-family: sans-serif;">
            <p style="font-size: 16px; font-weight: bold; margin-top: 0; color: #0f172a;">Dear ${inquiry.name},</p>
            <p style="color: #475569; margin-bottom: 24px;">
              We are pleased to inform you that your system audit consultation with CargoGrid's Senior Logistics Consultant has been <strong>Confirmed</strong>.
            </p>

            <div style="border: 2px dashed #e2e8f0; border-radius: 12px; padding: 24px; margin-bottom: 24px; background-color: #fafafa; text-align: center;">
              <span style="font-size: 11px; font-weight: bold; font-family: monospace; color: ${brandTeal}; text-transform: uppercase; letter-spacing: 0.1em; display: block; margin-bottom: 8px;">CONFIRMED MEETING SCHEDULE</span>
              <h2 style="margin: 0 0 12px 0; font-size: 18px; color: #0f172a; font-weight: 800;">
                ${meeting ? formatDateDisplay(meeting.scheduledTime, 'en') : 'Confirmed'}
              </h2>
              <p style="font-size: 13px; margin: 0 0 16px 0; color: #64748b;">
                Platform: <strong>${meeting?.platform || 'Google Meet'}</strong>
              </p>

              <a href="${meeting?.meetingUrl || '#'}" target="_blank" style="background-color: ${brandTeal}; color: #ffffff; padding: 10px 20px; font-weight: bold; text-decoration: none; border-radius: 6px; font-size: 12px; display: inline-block; box-shadow: 0 2px 4px rgba(0, 151, 178, 0.2);">
                Join Online Meeting Room &rarr;
              </a>
            </div>

            <p style="color: #475569; margin-bottom: 12px;">
              <strong>What should you prepare?</strong>
            </p>
            <ul style="color: #475569; font-size: 13px; padding-left: 20px; margin-bottom: 24px;">
              <li style="margin-bottom: 8px;">Current operational workflow drafts for RFQ, dispatch, and POD verification.</li>
              <li style="margin-bottom: 8px;">Examples of delayed or pending invoice cases from the past month.</li>
              <li style="margin-bottom: 8px;">Technical team representatives if you wish to see a live API integration showcase.</li>
            </ul>

            <p style="color: #475569; margin-bottom: 0;">
              For any urgent schedule adjustments, please reply to our Onboarding Partner team via WhatsApp. We look forward to analyzing your operational system!
            </p>
          </div>
          ${footerHtml}
        </div>
      ` : `
        <div style="${containerStyle}">
          ${headerHtml}
          <div style="background-color: #ffffff; padding: 32px 24px; font-family: sans-serif;">
            <p style="font-size: 16px; font-weight: bold; margin-top: 0; color: #0f172a;">Halo Bapak/Ibu ${inquiry.name},</p>
            <p style="color: #475569; margin-bottom: 24px;">
              Kami senang memberi kabar bahwa jadwal pertemuan konsultasi dan audit sistem logistik detail Anda bersama Senior Logistik Konsultan CargoGrid telah <strong>Dikonfirmasi</strong>.
            </p>

            <div style="border: 2px dashed #e2e8f0; border-radius: 12px; padding: 24px; margin-bottom: 24px; background-color: #fafafa; text-align: center;">
              <span style="font-size: 11px; font-weight: bold; font-family: monospace; color: ${brandTeal}; text-transform: uppercase; letter-spacing: 0.1em; display: block; margin-bottom: 8px;">JADWAL PERTEMUAN RESMI</span>
              <h2 style="margin: 0 0 12px 0; font-size: 18px; color: #0f172a; font-weight: 800;">
                ${meeting ? formatDateDisplay(meeting.scheduledTime, 'id') : 'Dikonfirmasi'}
              </h2>
              <p style="font-size: 13px; margin: 0 0 16px 0; color: #64748b;">
                Platform: <strong>${meeting?.platform || 'Google Meet'}</strong>
              </p>

              <a href="${meeting?.meetingUrl || '#'}" target="_blank" style="background-color: ${brandTeal}; color: #ffffff; padding: 10px 20px; font-weight: bold; text-decoration: none; border-radius: 6px; font-size: 12px; display: inline-block; box-shadow: 0 2px 4px rgba(0, 151, 178, 0.2);">
                Masuk ke Ruang Meeting Online &rarr;
              </a>
            </div>

            <p style="color: #475569; margin-bottom: 12px;">
              <strong>Apa yang perlu disiapkan?</strong>
            </p>
            <ul style="color: #475569; font-size: 13px; padding-left: 20px; margin-bottom: 24px;">
              <li style="margin-bottom: 8px;">Draf SOP alur operasional RFQ - Dispatch - POD di tim Anda saat ini.</li>
              <li style="margin-bottom: 8px;">Contoh kendala invoice pending paling lama yang dialami sebulan terakhir.</li>
              <li style="margin-bottom: 8px;">Delegasi dari tim IT jika Anda menginginkan demo API integrasi secara langsung.</li>
            </ul>

            <p style="color: #475569; margin-bottom: 0;">
              Jika ada perubahan jadwal mendadak, silakan hubungi tim Onboarding Partner kami di nomor WhatsApp CargoGrid Support. Sampai bertemu di agenda konsultasi!
            </p>
          </div>
          ${footerHtml}
        </div>
      `;

    default:
      return ``;
  }
}

// Internal labels mapping
export function getPainLabel(key: string, lang: 'id' | 'en' = 'id'): string {
  const isEn = lang === 'en';
  if (isEn) {
    const map: Record<string, string> = {
      rfq: "Slow RFQ & scattered rates",
      tracking: "Tracking status updates to customers",
      pod: "Delayed & misplaced proof of delivery (POD)",
      warehouse: "Inaccurate warehouse stock levels",
      billing: "Finance & billing issues",
      margin: "Unclear profit margin per job"
    };
    return map[key] || key;
  } else {
    const map: Record<string, string> = {
      rfq: "RFQ lambat & rate tersebar",
      tracking: "Update status tracking ke customer",
      pod: "Bukti POD terlambat & tercecer",
      warehouse: "Stok gudang tidak akurat",
      billing: "Keuangan & Invoice bermasalah",
      margin: "Margin keuntungan per job gelap"
    };
    return map[key] || key;
  }
}

export function getSektorLabel(key: string, lang: 'id' | 'en' = 'id'): string {
  const isEn = lang === 'en';
  if (isEn) {
    const map: Record<string, string> = {
      forwarder: "Freight Forwarding",
      '3pl': "3PL Warehouse",
      trucking: "Trucking Company",
      inhouse: "In-house Logistics (Shipper)",
      courier: "Courier / Last-Mile Delivery",
      other: "Other"
    };
    return map[key] || key;
  } else {
    const map: Record<string, string> = {
      forwarder: "Freight Forwarding",
      '3pl': "3PL Warehouse",
      trucking: "Trucking Company",
      inhouse: "In-house Logistics (Shipper)",
      courier: "Kurir / Last-Mile Delivery",
      other: "Lainnya"
    };
    return map[key] || key;
  }
}

export function getModuleLabel(key: string, lang: 'id' | 'en' = 'id'): string {
  const isEn = lang === 'en';
  if (isEn) {
    const map: Record<string, string> = {
      commercial: "Commercial (RFQ, CRM)",
      ops: "Operations (TMS, Dispatch)",
      tracking: "Customer Portal & Loyalty",
      finance: "Finance (Invoicing, Profitability)",
      warehouse: "Warehouse (WMS, Inventory)",
      hris: "HRIS & Service Ticketing",
      procurement: "Procurement & Vendor Management",
      analytics: "Intelligence & Enterprise Analytics"
    };
    return map[key] || key;
  } else {
    const map: Record<string, string> = {
      commercial: "Commercial (RFQ, CRM)",
      ops: "Operations (TMS, Dispatch)",
      tracking: "Customer Portal & Loyalty",
      finance: "Finance (Invoicing, Profitability)",
      warehouse: "Warehouse (WMS, Inventory)",
      hris: "HRIS & Service Ticketing",
      procurement: "Procurement & Vendor Management",
      analytics: "Intelligence & Enterprise Analytics"
    };
    return map[key] || key;
  }
}

export function formatDateDisplay(isoString: string, lang: 'id' | 'en' = 'id'): string {
  try {
    const d = new Date(isoString);
    if (lang === 'en') {
      const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
      const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
      const hours = d.getHours();
      const mins = String(d.getMinutes()).padStart(2, '0');
      const ampm = hours >= 12 ? 'PM' : 'AM';
      const formattedHours = hours % 12 || 12;
      return `${days[d.getDay()]}, ${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()} at ${formattedHours}:${mins} ${ampm}`;
    } else {
      const days = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"];
      const months = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"];
      return `${days[d.getDay()]}, ${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear()} pkl ${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')} WIB`;
    }
  } catch {
    return isoString;
  }
}
