import { FeatureItem, IcpItem, FlowStep, PackageItem, FaqItem } from "./types";

export const problemPoints = [
  {
    title: "RFQ Tercecer & Quote Lambat",
    titleEn: "Scattered RFQs & Slow Quotes",
    desc: "RFQ masuk lewat WhatsApp dan email pribadi, lambat ditanggapi, sehingga customer beralih ke kompetitor.",
    descEn: "RFQs enter via WhatsApp and personal emails, slow response leads customers to switch to competitors.",
    metric: "-45%",
    metricLabel: "Win Rate Opportunity",
    metricLabelEn: "Win Rate Opportunity",
  },
  {
    title: "Rate Vendor Manual di Excel",
    titleEn: "Manual Vendor Rates in Excel",
    desc: "Ribuan selling & buying rate tersebar di lembaran Excel, memicu resiko salah hitung costing dan kebocoran margin.",
    descEn: "Thousands of selling & buying rates are scattered across Excel sheets, risking costing errors and margin leakage.",
    metric: "12%",
    metricLabel: "Margin Risk Leakage",
    metricLabelEn: "Margin Risk Leakage",
  },
  {
    title: "Update Status Manual via Chat",
    titleEn: "Manual Status Updates via Chat",
    desc: "Operasional sibuk melayani telpon & chat customer yang menanyakan posisi barang dan status stock warehouse.",
    descEn: "Operations is busy answering customer calls & chats asking for cargo positions and warehouse stock status.",
    metric: "4-6 jam/hari",
    metricLabel: "Waktu Tim CS Terbuang",
    metricLabelEn: "CS Team Time Wasted",
  },
  {
    title: "POD Terlambat & Invoice Delay",
    titleEn: "Delayed POD & Invoice Delay",
    desc: "Kertas bukti tanda terima (POD) terselip atau lambat diserahkan supir, menunda pembuatan invoice dan memperpanjang DSO.",
    descEn: "Paper Proof of Delivery (POD) gets misplaced or submitted late by drivers, delaying invoice generation and prolonging DSO.",
    metric: "25+ hari",
    metricLabel: "Rata-rata DSO",
    metricLabelEn: "Average Days Sales Outstanding (DSO)",
  },
];

export const connectedFlowSteps: FlowStep[] = [
  {
    id: "rfq",
    number: 1,
    title: "RFQ & Inquiry",
    titleEn: "RFQ & Inquiry",
    description: "Satu inbox terpusat untuk semua inquiry masuk.",
    descriptionEn: "Centralized inbox for all incoming inquiries.",
    longDesc: "Tiap RFQ dari WhatsApp atau portal otomatis tercatat dengan timer SLA. Terbagi adil ke tim sales.",
    longDescEn: "Every RFQ from WhatsApp or portals is automatically logged with active SLA timers, evenly distributed to sales.",
    inputs: ["Nama Customer", "Detail Rute & Cargo", "Request Pick-up Date"],
    inputsEn: ["Customer Name", "Route & Cargo Details", "Requested Pick-up Date"],
    outputs: ["Inquiry Ticket Created", "Sales Agent Assigned", "SLA Timer Active"],
    outputsEn: ["Inquiry Ticket Created", "Sales Agent Assigned", "SLA Timer Active"],
    benefit: "Mengeliminasi inquiry hilang atau terlambat follow-up.",
    benefitEn: "Eliminates lost inquiries or late follow-ups.",
  },
  {
    id: "quote",
    number: 2,
    title: "Instant Quotation",
    titleEn: "Instant Quotation",
    description: "Hitung costing margin presisi secara instan.",
    descriptionEn: "Instantly calculate precise costing margins.",
    longDesc: "Sistem otomatis membandingkan rate vendor dan menghitung margin aman berdasarkan pricing rule perusahaan.",
    longDescEn: "The system automatically compares vendor rates and calculates safe margins based on company pricing rules.",
    inputs: ["Buying Rate Vendor", "Surcharge & Margin Rules", "Approval Flow"],
    inputsEn: ["Vendor Buying Rate", "Surcharge & Margin Rules", "Approval Flow"],
    outputs: ["Digital PDF Quotation", "Margin Margin Safe-Check", "Customer Email Sent"],
    outputsEn: ["Digital PDF Quotation", "Margin Safe-Check Passed", "Customer Email Sent"],
    benefit: "Kecepatan penawaran naik 5x dengan margin terkunci aman.",
    benefitEn: "Boosts quotation speed by 5x with locked safe margins.",
  },
  {
    id: "job",
    number: 3,
    title: "Job Booking & Dispatch",
    titleEn: "Job Booking & Dispatch",
    description: "Konversi otomatis quotation disetujui menjadi Job Order.",
    descriptionEn: "Auto-convert approved quotations into Job Orders.",
    longDesc: "Tanpa ketik ulang data cargo, sistem langsung membuat manifest pengiriman dan assign armada trucking atau container.",
    longDescEn: "Without retyping cargo details, the system instantly generates shipping manifests and assigns trucking or containers.",
    inputs: ["Confirmed Quote ID", "Trucking / Carrier Assignment", "Manifest Number"],
    inputsEn: ["Confirmed Quote ID", "Trucking / Carrier Assignment", "Manifest Number"],
    outputs: ["Job Order Created", "Driver Manifest Ready", "Vendor Purchase Order"],
    outputsEn: ["Job Order Created", "Driver Manifest Ready", "Vendor Purchase Order"],
    benefit: "Nol kesalahan input operasional dari sales ke divisi ops.",
    benefitEn: "Zero human errors in operations from sales handoff.",
  },
  {
    id: "wms",
    number: 4,
    title: "Warehouse Inventory",
    titleEn: "Warehouse Inventory",
    description: "Integrasi WMS terpusat untuk inbound & outbound.",
    descriptionEn: "Centralized WMS integration for inbound & outbound.",
    longDesc: "Jika pengiriman transit warehouse, sistem mengalokasikan rack/bin, membuat kode LPN, dan mencatat stock ledger.",
    longDescEn: "If shipment transits through a warehouse, the system allocates rack/bins, generates LPN codes, and updates the stock ledger.",
    inputs: ["Inbound Request", "Bin Location Assignment", "LPN Label Printing"],
    inputsEn: ["Inbound Request", "Bin Location Assignment", "LPN Label Printing"],
    outputs: ["Stock Ledger Entry", "Putaway Task Generated", "Real-Time Stock Balance"],
    outputsEn: ["Stock Ledger Entry", "Putaway Task Generated", "Real-Time Stock Balance"],
    benefit: "Akurasi stock warehouse terpantau langsung oleh customer.",
    benefitEn: "Real-time warehouse stock accuracy visible directly to customers.",
  },
  {
    id: "tracking",
    number: 5,
    title: "Tracking Milestone",
    titleEn: "Tracking Milestone",
    description: "Customer portal & tracking branded real-time.",
    descriptionEn: "Branded real-time customer portal & tracking.",
    longDesc: "Setiap update milestone dari supir atau ops otomatis memperbarui laman tracking berlogo brand Anda sendiri.",
    longDescEn: "Every milestone update from drivers or ops automatically updates the tracking page branded with your own logo.",
    inputs: ["Milestone Event", "Geocoding / GPS Location", "Exception Logs (Delay)"],
    inputsEn: ["Milestone Event", "Geocoding / GPS Location", "Exception Logs (Delay)"],
    outputs: ["Timeline Update", "Auto Customer WhatsApp", "Client Portal Tracking"],
    outputsEn: ["Timeline Update", "Auto Customer WhatsApp", "Client Portal Tracking"],
    benefit: "Zero-chat status. Customer memantau mandiri tanpa tanya CS.",
    benefitEn: "Zero-chat status. Customers self-serve without asking CS.",
  },
  {
    id: "pod",
    number: 6,
    title: "ePOD & Document Center",
    titleEn: "ePOD & Document Center",
    description: "Upload bukti serah terima (POD) instan.",
    descriptionEn: "Instant Proof of Delivery (POD) upload.",
    longDesc: "Driver memfoto POD fisik di lokasi lewat driver portal. Foto langsung tersinkron sebagai bukti tanda terima resmi.",
    longDescEn: "Drivers capture physical POD photos at the delivery location via the driver portal, syncing instantly as official proof.",
    inputs: ["Photo POD", "Receiver Signature", "Timestamp & GPS Coordinates"],
    inputsEn: ["Photo POD", "Receiver Signature", "Timestamp & GPS Coordinates"],
    outputs: ["POD Approved Status", "Customer Portal Ready to View", "SLA Fulfillment Recorded"],
    outputsEn: ["POD Approved Status", "Customer Portal Ready to View", "SLA Fulfillment Recorded"],
    benefit: "Bukti kirim masuk detik itu juga. Tanpa menunggu supir pulang.",
    benefitEn: "Proof of delivery captured in seconds, no waiting for drivers to return.",
  },
  {
    id: "billing",
    number: 7,
    title: "Billing Readiness",
    titleEn: "Billing Readiness",
    description: "Verifikasi kelengkapan dokumen pemicu tagihan.",
    descriptionEn: "Verify document completeness to trigger invoicing.",
    longDesc: "Sistem otomatis mendeteksi kecocokan POD & shipment cost, memberi sinyal bahwa order ini siap ditagihkan ke customer.",
    longDescEn: "System automatically checks POD and shipment cost matching, flagging the order as ready for customer billing.",
    inputs: ["Verified POD Attachments", "Shipment Final Cost", "Tax/Pajak Rule Setting"],
    inputsEn: ["Verified POD Attachments", "Shipment Final Cost", "Tax Rule Setting"],
    outputs: ["Billing-Ready Status", "E-Invoice Generated Draft", "AR Reconciliation Checklist"],
    outputsEn: ["Billing-Ready Status", "E-Invoice Generated Draft", "AR Reconciliation Checklist"],
    benefit: "Invoice-ready dalam 15 menit setelah barang sampai, memotong DSO.",
    benefitEn: "Invoice-ready in 15 minutes post-delivery, slashing DSO.",
  },
  {
    id: "accounting",
    number: 8,
    title: "Ledger Posting",
    titleEn: "Ledger Posting",
    description: "Buku besar operasional dan jurnal otomatis.",
    descriptionEn: "Automated general ledger and journal entries.",
    longDesc: "Invoice & vendor bill terposting ke General Ledger, memicu laporan trial balance, rugi-laba, dan neraca keuangan real-time.",
    longDescEn: "Invoices & vendor bills are posted to the General Ledger, instantly updating trial balance, P&L, and balance sheets.",
    inputs: ["Approved Invoice", "Chart of Accounts (COA)", "Posting Rules"],
    inputsEn: ["Approved Invoice", "Chart of Accounts (COA)", "Posting Rules"],
    outputs: ["Double-Entry Journal Logs", "Balance Sheet Updates", "Real-Time Profit/Loss Report"],
    outputsEn: ["Double-Entry Journal Logs", "Balance Sheet Updates", "Real-Time Profit/Loss Report"],
    benefit: "Audit-ready harian. Margin keuntungan terekam akurat.",
    benefitEn: "Daily audit-ready financials with accurate margins recorded.",
  },
];

export const icpList: IcpItem[] = [
  {
    id: "forwarder",
    title: "Freight Forwarder",
    titleEn: "Freight Forwarder",
    badge: "Lokal & Internasional",
    badgeEn: "Local & International",
    desc: "Pengelolaan logistik antarnegara dan antarpulau yang membutuhkan kalkulasi biaya yang rumit, pencocokan invoice vendor, dan respon RFQ super cepat.",
    descEn: "Cross-border and inter-island logistics management requiring complex cost calculations, vendor invoice matching, and lightning-fast RFQ response.",
    pains: [
      "Pembuatan quotation lambat karena rate vendor tersebar di Excel.",
      "Sulit melacak biaya tambahan (surcharge) sehingga margin bocor.",
      "CS habis waktu membalas status posisi container ke customer.",
    ],
    painsEn: [
      "Slow quotation generation because vendor rates are scattered in Excel.",
      "Difficult to track surcharges, leading to margin leakage.",
      "CS wastes time replying to customers about container position status.",
    ],
    pitch: "CargoGrid menyatukan CRM, RFQ inbox, procurement rate vendor, dan multi-leg shipment tracking. Margin per container terlihat jelas sejak quote dibuat hingga invoice terbit.",
    pitchEn: "CargoGrid unifies CRM, RFQ inbox, vendor procurement rates, and multi-leg shipment tracking. Margins per container are clearly visible from quotation draft to final invoice.",
    personaName: "Budi Santoso",
    personaRole: "Director / Owner",
    personaRoleEn: "Director / Owner",
    personaFocus: "Win-rate, Profit Margin, & Customer Experience",
    personaFocusEn: "Win-rate, Profit Margin, & Customer Experience",
    personaQuote: "Dulu kami butuh 24 jam untuk merespon RFQ luar negeri. Dengan CargoGrid, Sales kami bisa mengirimkan quote profesional dalam 10 menit dengan margin aman terkunci.",
    personaQuoteEn: "We used to need 24 hours to respond to overseas RFQs. With CargoGrid, our sales team can send professional quotes in 10 minutes with locked safe margins.",
  },
  {
    id: "3pl",
    title: "3PL Warehouse",
    titleEn: "3PL Warehouse",
    badge: "Storage & Fulfillment",
    badgeEn: "Storage & Fulfillment",
    desc: "Operator gudang yang melayani penyimpanan barang, pengelolaan inventaris pihak ketiga, serta proses inbound, outbound, dan stock opname.",
    descEn: "Warehouse operators handling third-party cargo storage, inventory management, inbound receipt, outbound pick/pack, and stock take.",
    pains: [
      "Customer sering komplain karena selisih stock report Excel.",
      "Kertas POD terselip, membuat penagihan sewa bulanan tertunda.",
      "Sulit melacak umur barang (stock aging) dan LPN di rak gudang.",
    ],
    painsEn: [
      "Frequent customer complaints due to discrepancies in Excel stock reports.",
      "Misplaced paper PODs, delaying monthly warehouse rent billing.",
      "Hard to track stock aging and License Plate Numbers (LPN) on warehouse racks.",
    ],
    pitch: "CargoGrid WMS menyambungkan aktivitas stock movement langsung ke customer portal. Customer bisa memantau stock balance mereka secara real-time dan mengunduh POD mandiri.",
    pitchEn: "CargoGrid WMS links real-time stock movements directly to the customer portal. Customers can monitor stock balance in real-time and download PODs independently.",
    personaName: "Hendry Wijaya",
    personaRole: "Warehouse Director",
    personaRoleEn: "Warehouse Director",
    personaFocus: "Stock Accuracy, Space Utilization, & Fast Billing",
    personaFocusEn: "Stock Accuracy, Space Utilization, & Fast Billing",
    personaQuote: "Akurasi stok gudang kami meroket jadi 99.8%. Customer kami tidak lagi menelpon untuk minta laporan mingguan, mereka tinggal login ke CargoGrid portal sendiri.",
    personaQuoteEn: "Our warehouse stock accuracy skyrocketed to 99.8%. Our customers no longer call us to request weekly reports—they just log into their CargoGrid portal.",
  },
  {
    id: "trucking",
    title: "Trucking & Distribusi",
    titleEn: "Trucking & Distribution",
    badge: "First & Last Mile",
    badgeEn: "First & Last Mile",
    desc: "Perusahaan armada darat yang melayani rute distribusi FTL (Full Truckload) maupun LTL (Less Than Truckload) ke berbagai cabang retail.",
    descEn: "Land transport companies handling FTL (Full Truckload) and LTL (Less Than Truckload) distribution routes to retail branches.",
    pains: [
      "Penugasan supir manual via WhatsApp, rentan miskomunikasi.",
      "Bukti POD fisik lambat kembali, membuat invoice tertunda berminggu-minggu.",
      "BBM dan biaya tol tidak tercatat rapi per perjalanan armada.",
    ],
    painsEn: [
      "Manual driver assignment via WhatsApp, prone to miscommunication.",
      "Slow physical POD return, delaying client invoicing for weeks.",
      "Fuel costs and tolls are not neatly tracked per vehicle trip.",
    ],
    pitch: "Kelola dispatching, digital manifest, driver portal PWA, hingga ePOD instan. Keberangkatan truk langsung memicu notifikasi pelacakan ke customer otomatis.",
    pitchEn: "Manage dispatching, digital manifests, PWA driver portal, and instant ePODs. Truck departures automatically trigger real-time tracking notifications for clients.",
    personaName: "Rian Ardiansyah",
    personaRole: "Head of Operations",
    personaRoleEn: "Head of Operations",
    personaFocus: "On-Time Delivery, Fleet Control, & Cashflow (DSO)",
    personaFocusEn: "On-Time Delivery, Fleet Control, & Cashflow (DSO)",
    personaQuote: "Kami berhasil memotong waktu tunggu POD dari 14 hari menjadi instan di hari yang sama. Arus kas (cashflow) perusahaan jadi jauh lebih sehat.",
    personaQuoteEn: "We successfully cut POD turnaround time from 14 days to instant same-day submission. Our company cashflow is much healthier.",
  },
  {
    id: "inhouse",
    title: "In-house Logistics",
    titleEn: "In-house Logistics",
    badge: "Shipper & Distributor",
    badgeEn: "Shipper & Distributor",
    desc: "Tim logistik internal manufaktur atau distributor besar yang mengelola banyak vendor transportir dan butuh efisiensi biaya serta SLA ketat.",
    descEn: "Internal logistics teams of manufacturers or large distributors managing multiple transport vendors who require cost efficiency and strict SLA compliance.",
    pains: [
      "Ketergantungan tinggi pada report manual dari masing-masing vendor transportir.",
      "Audit tagihan vendor sangat melelahkan karena harus dicocokkan satu per satu.",
      "SLA ketepatan waktu pengiriman vendor sulit diukur objektif.",
    ],
    painsEn: [
      "High dependency on manual performance reports from individual transport vendors.",
      "Vendor bill auditing is tedious as bills must be manually matched one-by-one.",
      "Vendor delivery on-time SLA is difficult to measure objectively.",
    ],
    pitch: "Satu dashboard netral untuk memantau performa semua transportir Anda. Konsolidasikan shipment tracking, validasi tagihan otomatis, dan pantau SLA ketat secara objektif.",
    pitchEn: "One neutral dashboard to track all your carriers' performance. Consolidate shipment tracking, automate bill validation, and monitor strict SLAs objectively.",
    personaName: "Dewi Lestari",
    personaRole: "Supply Chain Manager",
    personaRoleEn: "Supply Chain Manager",
    personaFocus: "Cost Savings, Vendor Accountability, & Audit Transparency",
    personaFocusEn: "Cost Savings, Vendor Accountability, & Audit Transparency",
    personaQuote: "Kami menghemat biaya logistik hingga 18% berkat visibilitas tarif vendor dan penalti SLA otomatis yang dihitung objektif oleh CargoGrid.",
    personaQuoteEn: "We saved up to 18% in logistics costs thanks to clear vendor rate visibility and automated SLA penalties calculated objectively by CargoGrid.",
  },
];

export const productModules = [
  {
    id: "crm",
    layer: "Fase Komersial",
    layerEn: "Commercial Layer",
    title: "CRM & RFQ Management",
    titleEn: "CRM & RFQ Management",
    desc: "Tangkap lead, kustom data customer, kelola pipeline opportunity sales, serta layani inbox RFQ logistik dalam satu platform kolaboratif.",
    descEn: "Capture leads, customize customer data, manage sales pipelines, and handle logistics RFQs in one collaborative inbox.",
    tags: ["Inquiry Ticketing", "Lead Pipe", "SLA Timer"],
    tagsEn: ["Inquiry Ticketing", "Lead Pipe", "SLA Timer"],
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "procurement",
    layer: "Fase Komersial",
    layerEn: "Commercial Layer",
    title: "Pricing & Rate Book",
    titleEn: "Pricing & Rate Book",
    desc: "Kelola rate kontrak ribuan vendor, tarif sewa truk, biaya pelabuhan (surcharge), hingga buying/selling rule dengan approval otomatis.",
    descEn: "Manage contract rates of thousands of vendors, truck rental rates, port surcharges, and buying/selling rules with automated approval flows.",
    tags: ["Contract Rates", "Cost Compare", "Auto-Margin Check"],
    tagsEn: ["Contract Rates", "Cost Compare", "Auto-Margin Check"],
    color: "from-indigo-500 to-violet-500",
  },
  {
    id: "operations",
    layer: "Fase Operasional",
    layerEn: "Operations Layer",
    title: "Job Execution & Dispatch",
    titleEn: "Job Execution & Dispatch",
    desc: "Konversi quote jadi job order instan. Buat manifest, bagikan rute perjalanan (multi-leg), serta delegasikan armada dan driver darat, laut, atau udara.",
    descEn: "Instantly convert quotes to job orders. Create manifests, assign multi-leg routes, and dispatch drivers and fleets across road, sea, or air.",
    tags: ["Digital Manifest", "Multi-Leg Route", "Driver PWA"],
    tagsEn: ["Digital Manifest", "Multi-Leg Route", "Driver PWA"],
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "wms",
    layer: "Fase Pergudangan",
    layerEn: "Warehouse Layer",
    title: "WMS & Putaway Ledger",
    titleEn: "WMS & Putaway Ledger",
    desc: "Multi-warehouse controller dengan navigasi rak/bin, cetak QR LPN label, inbound picking-packing, stok opname, serta kalkulasi storage billing otomatis.",
    descEn: "Multi-warehouse controller featuring bin allocations, QR LPN label printing, inbound pick & pack, stock take, and automatic storage billing.",
    tags: ["LPN Barcoding", "Bin Allocations", "Inventory Ledger"],
    tagsEn: ["LPN Barcoding", "Bin Allocations", "Inventory Ledger"],
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "portal",
    layer: "Fase Portal Customer",
    layerEn: "Customer Experience Layer",
    title: "Branded Customer Portal",
    titleEn: "Branded Customer Portal",
    desc: "Portal white-label berlogo perusahaan Anda. Customer bisa buat booking mandiri, lacak container, cek stock gudang, download POD, dan pantau tagihan.",
    descEn: "White-label client portal branded with your logo. Customers can book shipments, track containers, check stock, download PODs, and track bills.",
    tags: ["Branded Portal", "POD Self-Serve", "Order Booking"],
    tagsEn: ["Branded Portal", "POD Self-Serve", "Order Booking"],
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "finance",
    layer: "Fase Keuangan & Akuntansi",
    layerEn: "Finance & Accounting Layer",
    title: "Billing & ERP Accounting",
    titleEn: "Billing & ERP Accounting",
    desc: "Deteksi kesiapan tagihan dari validasi dokumen POD. Terbitkan invoice, hitung AR aging, monitor AP vendor, serta cetak laporan keuangan P&L harian.",
    descEn: "Detect billing readiness from POD document verification. Issue invoices, monitor AR aging, track vendor AP, and print daily P&L financial reports.",
    tags: ["Billing Readiness", "AR/AP Tracking", "GL General Ledger"],
    tagsEn: ["Billing Readiness", "AR/AP Tracking", "GL General Ledger"],
    color: "from-rose-500 to-orange-500",
  },
  {
    id: "platform",
    layer: "Konfigurasi Sistem",
    layerEn: "Platform Layer",
    title: "Sistem Konfigurasi Terintegrasi",
    titleEn: "Integrated System Configuration",
    desc: "Platform super fleksibel yang bisa diatur alur kerjanya, template PDF, format penomoran (naming sequence), hak akses (RBAC), hingga alert webhook.",
    descEn: "Super flexible platform to manage custom workflows, PDF templates, naming sequences, role-based access control (RBAC), and webhook alerts.",
    tags: ["White-Label Ready", "No-Code Config", "API & Webhooks"],
    tagsEn: ["White-Label Ready", "No-Code Config", "API & Webhooks"],
    color: "from-orange-500 to-amber-500",
  },
];

export const pricingPackages: PackageItem[] = [
  {
    id: "trackportal",
    name: "TrackPortal",
    priceMonthly: 2500000,
    priceAnnually: 2000000,
    desc: "Cocok untuk perusahaan logistik yang ingin mendigitalkan customer experience secara instan dengan branding mandiri.",
    descEn: "Perfect for logistics companies wanting to instantly digitalize their customer experience with independent branding.",
    positioning: "Branded tracking page dan POD access tanpa biaya develop mandiri.",
    positioningEn: "Branded tracking page and POD access with zero custom development costs.",
    fit: "Perusahaan Logistics & Broker Kecil",
    fitEn: "Small Logistics Companies & Freight Brokers",
    features: [
      "Branded Public Tracking Page",
      "Customer Portal Basic (POD Download)",
      "Upload ePOD via HP / Mobile Browser",
      "Up to 150 Shipment Tracking / bulan",
      "1 Custom Domain (tracking.perusahaan.com)",
      "Standard Email Notifications",
      "Web Support Ticket Response 24 jam",
    ],
    featuresEn: [
      "Branded Public Tracking Page",
      "Basic Customer Portal (POD Download)",
      "Upload ePOD via mobile phone / browser",
      "Up to 150 Shipment Tracking units / month",
      "1 Custom Domain (tracking.yourcompany.com)",
      "Standard Email Notifications",
      "Web Ticket Support with 24-hour SLA",
    ],
  },
  {
    id: "quoteops",
    name: "QuoteOps",
    priceMonthly: 6000000,
    priceAnnually: 4800000,
    desc: "Sangat pas untuk Freight Forwarder yang ingin merapikan alur RFQ masuk, rate vendor yang berserakan, dan memacu kecepatan sales.",
    descEn: "Highly suited for Freight Forwarders looking to organize incoming RFQ pipelines, messy vendor contract rates, and accelerate sales response.",
    positioning: "Dari inquiry ke penawaran harga (quotation) super cepat, presisi, dan margin aman.",
    positioningEn: "From initial customer inquiry to final digital quote: fast, precise, and margin-protected.",
    fit: "Freight Forwarder Lokal Berkembang",
    fitEn: "Growing Local Freight Forwarders",
    features: [
      "Commercial CRM (Leads, Accounts, Contacts)",
      "Centralized RFQ Ticketing Inbox",
      "Procurement Rate Book (Vendor Comparison)",
      "Margin Guardrail (Auto-detect penawaran rugi)",
      "Digital Quote Builder (Kirim PDF rapi sekali klik)",
      "Multi-currency & Surcharge management",
      "Sales Activity Logs & Win-Rate Dashboard",
    ],
    featuresEn: [
      "Commercial CRM (Leads, Accounts, Contacts)",
      "Centralized RFQ Ticketing Inbox",
      "Procurement Rate Book (Vendor rate comparison)",
      "Margin Guardrail (Auto-detect loss-making rates)",
      "Digital Quote Builder (One-click professional PDF quote)",
      "Multi-currency & Surcharge Management",
      "Sales Activity Logs & Win-Rate Analytics",
    ],
  },
  {
    id: "operations",
    name: "Operations Pro",
    priceMonthly: 15000000,
    priceAnnually: 12000000,
    desc: "ERP Operasional lengkap yang menghubungkan commercial dari penawaran harga langsung ke eksekusi armada, manifest jalan, supir, hingga siap tagih.",
    descEn: "Complete Operational ERP connecting sales quotation directly to fleet dispatching, digital manifests, drivers, tracking, and billing readiness.",
    positioning: "Shipment, tracking, POD, billing readiness, dan customer portal terkoneksi penuh.",
    positioningEn: "Fully integrated shipment execution, driver portal, ePOD capture, and billing readiness validation.",
    fit: "3PL, Trucking, & Forwarder Operasional Padat",
    fitEn: "High-Volume 3PL, Trucking, & Operational Forwarders",
    isPopular: true,
    features: [
      "Semua Fitur QuoteOps + TrackPortal",
      "Complete Job Order Management (Multi-Leg Route)",
      "Dispatching Center & Truck Manifest Darat",
      "Driver Portal App PWA (GPS updates & Photo ePOD)",
      "Billing Readiness Validator (POD matching trigger)",
      "Customer Portal Pro (Booking, Tracking, & Bill View)",
      "SLA Performance Tracker & Exception Log Alert",
    ],
    featuresEn: [
      "All Features in QuoteOps + TrackPortal",
      "Complete Job Order Management (Multi-Leg Routing)",
      "Dispatching Center & Land Truck Manifests",
      "PWA Driver Portal (GPS tracking & photo ePOD uploads)",
      "Billing Readiness Validator (POD document matching check)",
      "Pro Customer Portal (Bookings, Tracking, & Billing View)",
      "SLA Performance Tracker & Exception Log Alerts",
    ],
  },
  {
    id: "warehouse",
    name: "Warehouse WMS",
    priceMonthly: 18000000,
    priceAnnually: 14400000,
    desc: "Sistem Manajemen Pergudangan terintegrasi untuk 3PL fulfillment, logistik retail, atau pemilik barang yang butuh kendali stok ketat.",
    descEn: "Integrated Warehouse Management System (WMS) for 3PL fulfillment, retail logistics, or brand owners requiring strict stock oversight.",
    positioning: "Multi warehouse, rack/bin, LPN, inventory ledger, outbound, dan visibilitas stock harian.",
    positioningEn: "Multi-warehouse, rack/bin layout mapping, LPN control, inventory ledger, and live stock balance.",
    fit: "Warehouse Operator & Penyedia 3PL Gudang",
    fitEn: "Warehouse Operators & 3PL Warehouse Providers",
    features: [
      "Multi-Warehouse Management",
      "Rack & Bin Layout Allocation Mapping",
      "LPN (License Plate Number) & Barcoding Generator",
      "Putaway, Stock Transfer, & Picking List Flow",
      "FIFO, LIFO, Stock Aging & Expiry Tracker",
      "B2B Customer Stock Portal (Visibilitas Stok Mandiri)",
      "Storage Billing Estimator (Hitung tagihan sewa space)",
    ],
    featuresEn: [
      "Multi-Warehouse Management",
      "Rack & Bin Layout Allocation Mapping",
      "LPN (License Plate Number) & Barcode Label Generator",
      "Putaway, Stock Transfer, & Picking List Flow",
      "FIFO, LIFO, Stock Aging, and Expiration Trackers",
      "B2B Client Stock Portal (Self-Service Stock Visibility)",
      "Storage Billing Estimator (Automated space lease pricing)",
    ],
  },
  {
    id: "erpsuite",
    name: "ERP Suite",
    priceMonthly: 35000000,
    priceAnnually: 28000000,
    desc: "Satu sistem logistik utuh terintegrasi dari hulu ke hilir. Menghubungkan divisi sales, ops, warehouse, billing, perpajakan, hingga akuntansi ledger keuangan.",
    descEn: "End-to-end unified logistics ERP. Connects commercial sales, operations, warehousing, invoicing, taxes, and accounting ledger.",
    positioning: "Unifikasi Commercial, Operations, Warehouse, Finance, Accounting, Portal, & Loyalty.",
    positioningEn: "Total unification of Commercial, Operations, WMS, Finance, Accounting, Client Portal, and Loyalty Engines.",
    fit: "SaaS Enterprise Logistik Skala Menengah ke Atas",
    fitEn: "Mid-to-Large Scale Enterprise Logistics & Shippers",
    features: [
      "Gabungan Seluruh Modul Operations & WMS",
      "Operational Accounting Module",
      "COA (Chart of Accounts), GL (Buku Besar), & Jurnal Otomatis",
      "Real-time Financial Reports (P&L, Balance Sheet, Trial Balance)",
      "B2B Loyalty Tier, Point Rewards, & Margin-safe Cashback Rules",
      "Event-based WhatsApp Notification Integration (Kirim update otomatis)",
      "Unlimited Open API & Webhook Integrations",
    ],
    featuresEn: [
      "Complete combination of Operations & WMS Modules",
      "Operational Accounting Module",
      "COA (Chart of Accounts), GL, and automated double-entry journals",
      "Real-time Financial Statements (P&L, Balance Sheet, Trial Balance)",
      "B2B Loyalty Tiers, Points Rewards, and Safe Cashback Rules",
      "Event-based Automated WhatsApp & Email Notifications",
      "Unlimited Open API & Webhook Integrations",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise Custom",
    priceMonthly: 75000000,
    priceAnnually: 60000000,
    desc: "Didesain khusus untuk korporasi besar yang membutuhkan penyesuaian khusus, infrastruktur terisolasi, integrasi legacy system, dan SLA tingkat tinggi.",
    descEn: "Custom-tailored for large corporate enterprises requiring unique workflows, isolated infrastructure, legacy integrations, and maximum SLAs.",
    positioning: "Dedicated Cloud Infra, Single Sign-On, integrasi kustom tanpa hambatan.",
    positioningEn: "Dedicated cloud infrastructure, corporate SSO, and seamless legacy API integrations.",
    fit: "Korporat Multinasional & BUMN Logistik",
    fitEn: "Multinational Corporations & State-Owned Logistics Enterprises",
    features: [
      "Dedicated Cloud Infrastructure (Private Server)",
      "Custom Legacy System Integration (ERP Oracle, SAP, AS400)",
      "Enterprise Identity Provider Single Sign-On (SSO / SAML)",
      "Custom Workflow & Custom Reporting Builder",
      "Contractual 99.9% Server Uptime SLA Guarantee",
      "24/7 Dedicated Account Technical Manager",
      "On-site Implementation, Data Migration & Staff Training",
    ],
    featuresEn: [
      "Dedicated Cloud Infrastructure (Isolated Private Server)",
      "Custom Legacy System Integration (Oracle, SAP, AS400)",
      "Enterprise Identity Provider Single Sign-On (SAML / SSO)",
      "Custom Workflow Engine & Proprietary Report Builder",
      "Contractual 99.9% Server Uptime SLA Guarantee",
      "24/7 Dedicated Technical Account Manager Support",
      "On-site Implementation, Full Data Migration, and Staff Training",
    ],
  },
];

export const faqList: FaqItem[] = [
  {
    id: "faq1",
    question: "Apakah CargoGrid menggantikan software accounting yang sudah kami gunakan?",
    questionEn: "Does CargoGrid replace our existing accounting software?",
    answer: "CargoGrid bisa bertindak sebagai software accounting penuh untuk paket ERP Suite karena kami memiliki Chart of Accounts (COA), General Ledger (GL), dan pencatatan jurnal otomatis. Namun, jika Anda ingin tetap menggunakan sistem eksternal seperti SAP, Oracle, Xero, Accurate, atau MYOB, CargoGrid sangat fleksibel dan dapat dikonfigurasi sebagai operational finance layer yang menyiapkan invoice evidence, pencocokan AR/AP, lalu menyalurkan ringkasan jurnal tersebut melalui API.",
    answerEn: "CargoGrid can act as a fully fledged financial accounting software in the ERP Suite package since we provide a built-in Chart of Accounts (COA), General Ledger (GL), and automated journal postings. However, if you prefer to keep using your external packages like SAP, Oracle, Xero, Accurate, or MYOB, CargoGrid is highly modular and can be configured as an operational finance layer that prepares invoice evidence, handles AR/AP matching, and streams summarized journal entries via API.",
  },
  {
    id: "faq2",
    question: "Apakah kami bisa berlangganan modul tracking dan portal customer saja?",
    questionEn: "Can we subscribe to just the tracking and customer portal modules?",
    answer: "Tentu saja! Paket TrackPortal didesain khusus bagi perusahaan logistik yang ingin cepat memiliki website pelacakan berlogo brand sendiri serta akses portal download POD tanpa harus mengganti seluruh sistem internalnya. Anda bisa menginput data tracking manual atau mengunggahnya via Excel, lalu mengaktifkan modul lainnya secara bertahap seiring perkembangan kebutuhan bisnis Anda.",
    answerEn: "Absolutely! The TrackPortal package is specially designed for logistics companies wanting to quickly publish a branded tracking website and enable self-service POD downloads without altering their entire internal system. You can input shipment milestones manually or upload them via Excel, and upgrade to more modules as your company grows.",
  },
  {
    id: "faq3",
    question: "Apakah alur kerja status dan template dokumen bisa disesuaikan dengan SOP kami?",
    questionEn: "Can shipment status workflows and document templates be customized to our SOP?",
    answer: "Ya. Salah satu kekuatan utama CargoGrid adalah sifatnya yang dapat dikonfigurasi penuh oleh Administrator. Anda tidak perlu menghubungi programmer kami hanya untuk mengubah urutan status shipment (milestone), menyesuaikan formula nomor invoice, mengatur batas approval diskon, atau merancang ulang layout surat jalan. Semua konfigurasi tersebut dapat dikelola langsung di panel admin utama.",
    answerEn: "Yes. One of the main strengths of CargoGrid is its highly configurable nature. As an Admin, you do not need to contact our developers to modify milestone state sequences, adjust invoice number patterns, set discount approval thresholds, or redesign delivery note layouts. All settings are manageable directly inside the main administrator dashboard.",
  },
  {
    id: "faq4",
    question: "Apakah modul warehouse WMS mendukung scan barcode/QR code via HP?",
    questionEn: "Does the warehouse WMS module support scanning barcodes or QR codes via smartphone?",
    answer: "Ya, CargoGrid WMS dirancang mobile-responsive dan mendukung scan barcode atau QR Code untuk mencatat LPN (License Plate Number) langsung lewat kamera smartphone atau perangkat mobile terminal scanner (Android/iOS). Ini memudahkan proses inbound receiving, putaway penempatan rak, stock opname harian, hingga pick & pack outbound pengeluaran barang tanpa memerlukan kabel.",
    answerEn: "Yes, CargoGrid WMS is designed to be fully mobile-responsive and supports barcode or QR code scanning to register License Plate Numbers (LPN) directly using smartphone cameras or mobile scanner terminals (Android/iOS). This facilitates cord-free operations for inbound receiving, rack putaway, stock take, and outbound pick & pack.",
  },
  {
    id: "faq5",
    question: "Berapa lama waktu yang dibutuhkan untuk proses implementasi dan live system?",
    questionEn: "How long does implementation take until the system goes live?",
    answer: "Untuk paket TrackPortal, proses setup domain kustom dan onboarding mandiri bisa diselesaikan dalam 1-3 hari kerja. Untuk paket Operations, WMS, dan ERP Suite, biasanya memerlukan waktu 2 hingga 4 minggu untuk proses pemetaan alur SOP (workflow mapping), migrasi master data dari Excel lama, training staf operasional Anda, serta masa uji coba pilot pengiriman pertama.",
    answerEn: "For the TrackPortal package, custom domain configuration and self-onboarding takes only 1-3 business days. For the Operations, WMS, and ERP Suite packages, it generally takes 2 to 4 weeks to map workflows, migrate master data from old Excel sheets, train operational staff, and perform pilot run shipments.",
  },
  {
    id: "faq6",
    question: "Bagaimana dengan keamanan data kami dan data customer kami?",
    questionEn: "How secure is our data and our customers' data?",
    answer: "CargoGrid memperlakukan keamanan data sebagai prioritas utama. Seluruh transmisi data dienkripsi dengan SSL/TLS 256-bit standar perbankan. Data antarsubsidiari atau tenant terisolasi secara aman menggunakan sistem multi-tenant yang ketat. Untuk paket Enterprise, kami juga menyediakan opsi penempatan private cloud dedicated dengan database terisolasi serta sistem otentikasi Single Sign-On (SSO).",
    answerEn: "CargoGrid treats data security as our highest priority. All data in transit is encrypted using bank-grade 256-bit SSL/TLS. Tenant data is isolated securely using strict multi-tenant partitions. For Enterprise clients, we offer dedicated private cloud deployments with fully isolated databases and SAML Single Sign-On (SSO).",
  },
  {
    id: "faq7",
    question: "Apakah ada biaya tersembunyi seperti biaya penambahan user?",
    questionEn: "Are there any hidden costs, such as extra fees for adding users?",
    answer: "Kami percaya pada transparansi harga. Seluruh harga paket yang tertera di website kami didasarkan pada fungsionalitas fitur dan batasan volume transaksi bulanan, bukan jumlah user. Anda bisa menambahkan user (staff, driver, customer, vendor) sebanyak-banyaknya tanpa perlu khawatir membayar biaya lisensi per user tambahan.",
    answerEn: "We believe in transparent pricing. All packages on our website are based on features and monthly transaction volumes rather than user seats. You can add as many users (internal staff, drivers, customers, vendors) as you like without worrying about per-seat licensing fees.",
  },
];
